### PR TITLE
ENT-7442 Fixup zypper package module script to work properly with interpreter attribute

### PR DESCRIPTION
**Pull request by craigcomstock**
Same change as included in masterfiles commit

ef02bcb265b7a285b280efddb87413f68372ba2e

which covered apt_get and yum but missed zypper.

Ticket: ENT-7442
Changelog: title

### CODE REVIEW

**Review by nickanderson — APPROVED** [review]

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6867/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6867/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6867/

**Comment by craigcomstock** [comment]
cherry picks
3.18.x: https://github.com/cfengine/masterfiles/pull/2027 
3.15.x: https://github.com/cfengine/masterfiles/pull/2028

**Comment by nickanderson** [comment]
Backported: 
image

**Comment by nickanderson** [comment]
I see @craigcomstock and i have a race condition

**Pull request merged**
