### PR TITLE
Add "contain => silent" to hub php cli_tasks commands to eliminate noise

### PR DESCRIPTION
**Pull request by atsaloli**
Changelog: None

See also: https://tracker.mender.io/browse/CFE-2921

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by atsaloli** [comment]
FYI @nickanderson

**Comment by atsaloli** [comment]
@nickanderson how's this look?

**Comment by nickanderson** [comment]
Hi @atsaloli, I am going to take this as part of a different PR.

See https://github.com/cfengine/masterfiles/pull/1333

Thanks!

**Comment by atsaloli** [comment]
Okay

**Pull request closed without merging**
