### PR TITLE
ENT-8456: Adapt the cf-serverd.service template to the version from core

### PR DESCRIPTION
**Pull request by vpodzime**
Reflecting the changes from https://github.com/cfengine/core/commit/962bac57c2af.

Merge together:
https://github.com/cfengine/core/pull/5045
https://github.com/cfengine/masterfiles/pull/2485

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @nickanderson can review this?

**Review by olehermanse — APPROVED** [review]
LGTM

**Review by craigcomstock — APPROVED** [review]

**Review by craigcomstock — CHANGES_REQUESTED** [review]
Which core file does this try to duplicate? https://github.com/cfengine/core/blob/master/misc/systemd/cf-serverd.service.in is different than this one you propose.

Might be nice to add some links back and forth so we know what's going on here. I assume we take the service files from core for packaging? And then later after bootstrap, masterfiles could overwrite with what it has?

**Comment by vpodzime** [comment]
> Might be nice to add some links back and forth so we know what's going on here.

The commit has a link to the related commit in core that changes the file.

**Comment by vpodzime** [comment]
> I assume we take the service files from core for packaging? And then later after bootstrap, masterfiles could overwrite with what it has?

I'm not sure how this works and I don't want to care. :) I'm just trying to keep things consistent between the two places.

**Comment by craigcomstock** [comment]
> > I assume we take the service files from core for packaging? And then later after bootstrap, masterfiles could overwrite with what it has?
> 
> I'm not sure how this works and I don't want to care. :) I'm just trying to keep things consistent between the two places.

Interesting. The link, https://github.com/cfengine/core/commit/3ccb427e933a5, is 404 for me and the file I referenced in core certainly is not the same as what you have here. I do think what you have here looks like an improvement though, so maybe double-back and fix the other spots?

**Review by craigcomstock — CHANGES_REQUESTED** [review]
Fixup link to core change in comment/PR description, it is 404 for me. 

Also maybe fix the core version I linked to as well since it doesn't agree with this one.

**Comment by vpodzime** [comment]
> Fixup link to core change in comment/PR description, it is 404 for me.

Oh, there was a rebase. It should be cfengine/core@962bac57c2af

**Comment by vpodzime** [comment]
> Also maybe fix the core version I linked to as well since it doesn't agree with this one.

I'm changing both files at the same time. Here and in the related core PR.

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
