### PR TITLE
first pass at snapcraft package module

### PR DESCRIPTION
**Pull request by josephholsten**
I'm playing with this locally, but obviously we'd want some tests, doc &c

### CODE REVIEW

**Comment by nickanderson** [comment]
Nifty

**Comment by nickanderson** [comment]
Do you want to open an issue in https://tracker.mender.io to track this?

Would be nice to see some example usage and output as well.

**Comment by josephholsten** [comment]
Example usage I have:

```cfengine
bundle agent install_ripgrep
{
packages:
  "rg"
    policy => "present",
    package_module => snap;
}
```

What output are you asking about? Pardon my ignorance, I'd been cfengining for about 6 hours when I wrote this.

I'll go investigate the jira!

**Comment by vpodzime** [comment]
Any progress on this one @josephholsten?

**Comment by josephholsten** [comment]
@vpodzime I'm sorry, I dropped this. I'm setting up a jira ticket now!

**Comment by josephholsten** [comment]
@vpodzime @nickanderson I've created https://tracker.mender.io/browse/CFE-2811. What can I do next to help finish this out?

**Comment by vpodzime** [comment]
@josephholsten could you please address the above questions? I'd like this PR to get merged or closed soon.

**Comment by nickanderson** [comment]
Ping @josephholsten

**Comment by nickanderson** [comment]
I will try to move this forward in another PR https://github.com/cfengine/masterfiles/pull/1532

Thanks!

**Pull request closed without merging**
