### PR TITLE
ENT-5281 Do not bind to "::" on RHEL/CentOS 5 by default (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-5281
Changelog: Title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5194/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5194/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5194/

**Comment by nickanderson** [comment]
Is this a cherry pick? I don't see the -x reference in the commit

**Comment by craigcomstock** [comment]
will re-work as a cherry-pick.

**Pull request closed without merging**
