### PR TITLE
Backport ha improvements

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
@pasinskim is this deprecated by your other HA PR?

**Comment by pasinskim** [comment]
No. Those changes are still valid.

**Comment by pasinskim** [comment]
After merging this stuff you can also cherry-pick https://github.com/pasinskim/masterfiles/commit/77b238f8d08a6f5cf693130bc929bdfc11f3c4d9

**Pull request merged**
