### PR TITLE
Revert "CFE-2429/master: Manage cfengine components via policy on systemd managed hosts"

### PR DESCRIPTION
**Pull request by olehermanse**
Reverts cfengine/masterfiles#1522

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2841/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2841/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2841/

**Comment by olehermanse** [comment]
@cf-bottom I want another jenkins build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2842/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2842/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2842/

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2844/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2844/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2844/

**Pull request merged**
