### PR TITLE
Add pkgsrc package module. See http://www.pkgsrc.org/

### PR DESCRIPTION
**Pull request by kacfengine**
Supersedes https://github.com/cfengine/masterfiles/pull/569.

### CODE REVIEW

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by bahamat** [comment]
Excellent! Will this also be merged into 3.8.x and 3.7.x branches?

**Comment by kacfengine** [comment]
I'm afraid not. :-( We have a strict policy of not integrating new features in patch series. I know it sucks a bit, but we would rather not make exceptions to this rule.

So people will have to fetch it manually for now, but it's quite easy to drop into the modules directory, and 3.9 is not *that* far away, should be here somewhere in June.

Thanks for the work!

**Comment by bahamat** [comment]
I find this pretty frustrating since I busted my ass to get it ready for 3.8 and this PR sat for weeks with no feedback and no activity. And after several attempts to move things along I finally pressed the issue and it was merged in a couple of days, but not before 3.8 was cut. And so now it will again sit for *nearly a year* before release.

**Comment by kacfengine** [comment]
Yes, I know. Believe me, we are well aware of the capacity problems when it comes to pull requests, it is an unfortunate, but very real resource problem. We have discussed internally how we can handle pull requests if not faster, then at least more predictably, but it's still an ongoing discussion.

And to be clear, 3.9 is six months away, not a year.

**Comment by bahamat** [comment]
June is 7 months away, plus the month that it has already sat.

**Pull request merged**
