### PR TITLE
Fix Masterfiles travis failures

### PR DESCRIPTION
**Pull request by olehermanse**
@jimis Maybe this fixes it?

### CODE REVIEW

**Comment by jimis** [comment]
This change looks good, but it's not enough. When `testall`  invokes `testall --bindir` then cf-net binary fails is not found and that one fails. This happens because we install packages of 3.10 and 3.7 here that don't have cf-net at all.

Another change is needed, maybe in core cf-net binary could be optional.

**Comment by olehermanse** [comment]
@jimis cf-net doesn't exist in 3.10. So I think core is correct as is? cf-net exists in master and 3.11, not 3.10 or 3.7

**Comment by olehermanse** [comment]
@nickanderson @jimis So the problem here is that we're testing 3.10 package with 3.11 tests / testall. My suggestion is to comment out the latest/master test case for now, and re-enable it when 3.11 includes cf-net. We can run into the same error if we add new features with tests, but we also kind of want to test master with latest, even though they can be quite different.

**Comment by nickanderson** [comment]
Well at least I find the actual versions easier to read than lts/oldlts.

We do need want to make sure that 3.11 MPF works on 3.10, and 3.7 binaries (because of upgrade)

**Comment by jimis** [comment]
This is a good compromise. We should remember to uncomment the top session when 3.11 is out, in both 3.11 and master branches.

**Comment by nickanderson** [comment]
This should be picked into 3.11 3.10  and 3.7 branches?

**Comment by olehermanse** [comment]
@nickanderson The cf-net commit should only be in 3.11.x and master. The others you can try to cherry pick back.

**Pull request merged**
