### PR TITLE
ENT-6219 Added standalone self upgrade capability for Windows agents (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
Also includes commented out code to use msiexec.bat packages module when ENT-6823 is resolved.

Since this policy is standalone several msiexec bits had to be copied here

Ticket: ENT-6219
Changelog: title
(cherry picked from commit a6cfc5725d212bd86961d6b83999b1304ad4be42)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6212/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6212/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6212/

**Comment by craigcomstock** [comment]
Retrying sequential-tests and fr-tests, maybe failed due to rate limit due to running at same time as nightlies.

**Comment by craigcomstock** [comment]
dang. sequential-test failures are known issues right now. :( I suppose I can work on addressing those FIRST :)

https://tracker.mender.io/browse/ENT-6852 (mysterious bootstrap failures with no debug logs in test log)
https://tracker.mender.io/browse/ENT-6839 (cfengine service start failing in upgrade test on CFE version 3.10.7)

**Comment by craigcomstock** [comment]
> dang. sequential-test failures are known issues right now. :( I suppose I can work on addressing those FIRST :)
> 
> https://tracker.mender.io/browse/ENT-6852 (mysterious bootstrap failures with no debug logs in test log)
> https://tracker.mender.io/browse/ENT-6839 (cfengine service start failing in upgrade test on CFE version 3.10.7)

I think this PR, https://github.com/cfengine/system-testing/pull/378, will resolve both of these issues. :) So waiting on review/merge of that and then will re-run this and 3.12.x PRs for ENT-6219 back port.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6240/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6240/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6240/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6259/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6259/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6259/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6273/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6273/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6273/

**Review by nickanderson — APPROVED** [review]

**Pull request merged**
