### PR TITLE
ENT-6115 Added check for aws ec2 metadata content to make CI more reliable

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-6115
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5476/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5476/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5476/

**Comment by nickanderson** [comment]
LGTM

**Comment by craigcomstock** [comment]
I suspect that masterfiles PR builds don't work with sequential-tests upgrade tests. See ENT-6129.

**Comment by nickanderson** [comment]
Shoudl we pick this one back to 3.15 and 3.12?

**Comment by craigcomstock** [comment]
3.15.x fix is easy, 3.12.x MPF still uses curl command so doesn't apply cleanly. Thoughts @nickanderson ? `url_get` is certainly available so we could port the whole bundle `cfe_autorun_inventory_aws_ec2_metadata_cache` back to 3.12.x as-is from master?

**Comment by nickanderson** [comment]
> 3.15.x fix is easy, 3.12.x MPF still uses curl command so doesn't apply cleanly. Thoughts @nickanderson ? `url_get` is certainly available so we could port the whole bundle `cfe_autorun_inventory_aws_ec2_metadata_cache` back to 3.12.x as-is from master?

Yes, I think we can.

url_get was introduced in 3.8, so we should be able to backport the current master as it to 3.12.

**Comment by olehermanse** [comment]
3.15.x cherry-pick: https://github.com/cfengine/masterfiles/pull/1850

**Comment by nickanderson** [comment]
> 3.15.x cherry-pick: #1850

Merged #1850

**Pull request merged**
