### PR TITLE
3.12.x PR

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @nickanderson can review this?

**Comment by Lex-2008** [comment]
@nickanderson : this is a backport of your fix for https://tracker.mender.io/browse/ENT-4250 to 3.12.x branch. Any objections for merging?

**Comment by nickanderson** [comment]
Why do we need to backport this? I thought only master was affected?

**Comment by vpodzime** [comment]
@Lex-2008 can we get a follow-up that fixes the one remaining issue with permissions? Policy @nickanderson added still fixes something there.

**Comment by Lex-2008** [comment]
I don't really understand you, @vpodzime - this is a backport of Nick's changes done in master PR: https://github.com/cfengine/masterfiles/pull/1265, also mirrored in postinst scripts: https://github.com/cfengine/buildscripts/pull/483 (3.10.x branch) https://github.com/cfengine/buildscripts/pull/493 (3.12.x branch) https://github.com/cfengine/buildscripts/pull/482 (master branch).

Or do you mean that in general there are some changes done by policy that should also be performed by postinst scripts? That's a task for a separate ticket.

**Comment by vpodzime** [comment]
> Or do you mean that in general there are some changes done by policy that should also be performed by postinst scripts? That's a task for a separate ticket.

Yes, I meant this. Sorry for the confusion, I thought this was the backport of the fixes for scriptlets. I'm just trying to make sure we fix it properly in both places.

**Comment by Lex-2008** [comment]
Yes, we do! All PRs are linked from the ticket: https://tracker.mender.io/browse/ENT-4250 (the ticket is not always linked from PRs, sadly)

**Pull request merged**
