### PR TITLE
ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs (3.18)

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1064

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
Rebased https://github.com/cfengine/buildscripts/pull/1064

@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8048/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8048/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8048/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Pull request merged**
