### PR TITLE
ENT-5752  Always update modules from masterfiles to $(sys.workdir)/modules (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
Previously only distribution packages would cause modules to be upgraded.

Now new versions of masterfiles will also cause modules to be upgraded.

3.15.x cherry pick required cherry picking change from `$(sys.bindir)/python`
to `$(sys.bindir)/cfengine-selected-python` (CFE-3512) in order to apply more cleanly.

Commit for CFE-3512: https://github.com/cfengine/masterfiles/commit/a864d5cced81b37cf0f0ed9e61d392bd6ed96194

Ticket: ENT-5752
Changelog: title
(cherry picked from commit 225f5c0)

Conflicts:
	cfe_internal/update/update_policy.cf
	lib/packages.cf
	modules/packages/Makefile.am

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @nickanderson can review this?

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6811/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6811/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6811/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6816/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6816/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6816/

**Comment by craigcomstock** [comment]
fr-tests failure seems related to known issue, will ignore for now.

**Comment by craigcomstock** [comment]
Tested a few more things with the latest build and it looks good to me.

**Review by vpodzime — COMMENTED** [review]
Please squash the backward-compatibility commits. Looks good to me otherwise. Just please make sure updates work across versions.

**Comment by craigcomstock** [comment]
> Please squash the backward-compatibility commits. Looks good to me otherwise. Just please make sure updates work across versions.

Cool. I squashed the compat commits into one and left the others as-is. Look good @vpodzime ?

**Comment by craigcomstock** [comment]
@vpodzime I tested this masterfiles with 3.12.8 binaries on policy server and client and things looked OK. I tested a custom apt_get module as well as random other subdirs of modules being propogated around and purged with `"cfengine_internal_purge_policies": [ "any" ]` in def.json classes.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by vpodzime** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6853/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6853/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6853/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6855/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6855/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6855/

**Pull request merged**
