### PR TITLE
ENT-8523: Stopped loading Apache mod_deflate by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1025

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Review by Lex-2008 — APPROVED** [review]

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7868/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7868/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7868/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7871/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7871/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7871/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7873/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7873/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7873/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7878/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7878/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7878/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7884/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7884/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7884/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7902/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7902/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7902/

**Comment by nickanderson** [comment]
@aleksandrychev, @craigcomstock 

This pr _removing_ `mod_deflate` from the default Enterprise Apache config passed all but that pesky triple upgrade test that has been failing on us. Shall I go ahead and merge?

**Comment by nickanderson** [comment]
@Lex-2008  re-affirmed OK to merge with this triple upgrade failure.

**Pull request merged**
