### PR TITLE
CFE-2458: Allow specification of files_single_copy via augments

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
@jimis or @kacf any idea about this autogen failure all the sudden?

**Comment by kacf** [comment]
Can't say that I do, but it must be related to the `determine-version.sh` script. Can you try running it locally while at the same commit and see what result it gives?

**Comment by nickanderson** [comment]
@kacf it works locally on that commit, and it also works in 3.10.x

**Comment by kacf** [comment]
I can't reproduce it even in a Ubuntu 12 docker instance, which is what Travis uses. Also the message `fatal: No tags can describe '9884667a989ffa87f4975df25a5d00113ce5cf8e'.` is completely bogus, clearly it can be described. I don't have any other explanation than that Travis is using a buggy version of Git. Maybe you can tweak exactly which container Travis uses for doing the build.

**Comment by nickanderson** [comment]
@jimis thoughts?

**Pull request merged**
