### PR TITLE
CFE-3568: Various fix-ups for FreeBSD pkg module (master)

### PR DESCRIPTION
**Pull request by nickanderson**
Originally proposed in https://github.com/cfengine/masterfiles/pull/1886 by @gpiero (Thank you!).

I altered the commit messages to align with our CONTRIBUTING guidelines.

This PR supersedes https://github.com/cfengine/masterfiles/pull/1886

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6322/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6322/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6322/

**Comment by gpiero** [comment]
Sorry @nickanderson, I've just committed a new patch [https://github.com/gpiero/masterfiles/commit/a9792ba47cb2fdc2d5537ab7f60bf4aa323ebb62] before realizing the PR has been superseeded. Do you want me to open a new PR for that?

**Comment by nickanderson** [comment]
> Sorry @nickanderson, I've just committed a new patch [https://github.com/gpiero/masterfiles/commit/a9792ba47cb2fdc2d5537ab7f60bf4aa323ebb62] before realizing the PR has been superseeded. Do you want me to open a new PR for that?

Yes please. It would be great if we can also get a ticket for that one and some output/example showing behavior before/after.

**Comment by nickanderson** [comment]
@gpiero ^

**Comment by nickanderson** [comment]
@olehermanse @vpodzime I don't think this valgrind failure is related to this change.

```
Running cf-check dump:
+ echo 'Running cf-check dump:'
+ valgrind --leak-check=full --track-origins=yes --error-exitcode=1 /var/cfengine/bin/cf-check dump
+ grep -E '\s*[{}"]' --invert-match
+ tee cf_check_dump.txt
==22048== Memcheck, a memory error detector
==22048== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22048== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==22048== Command: /var/cfengine/bin/cf-check dump
==22048== 
    info: No filenames specified, defaulting to .lmdb files in /var/cfengine/state
/var/cfengine/state/cf_state.lmdb:
/var/cfengine/state/cf_lastseen.lmdb:
/var/cfengine/state/packages_installed_$(package_module_knowledge.platform_default).lmdb:
/var/cfengine/state/cf_lock.lmdb:
/var/cfengine/state/cf_observations.lmdb:
/var/cfengine/state/nova_static.lmdb:
Error: This database contains unknown binary data - use --simple to print anyway
==22048== 
==22048== HEAP SUMMARY:
==22048==     in use at exit: 1,717 bytes in 21 blocks
==22048==   total heap usage: 2,661 allocs, 2,640 frees, 139,963 bytes allocated
==22048== 
==22048== LEAK SUMMARY:
==22048==    definitely lost: 0 bytes in 0 blocks
==22048==    indirectly lost: 0 bytes in 0 blocks
==22048==      possibly lost: 0 bytes in 0 blocks
==22048==    still reachable: 1,717 bytes in 21 blocks
==22048==         suppressed: 0 bytes in 0 blocks
==22048== Reachable blocks (those to which a pointer was found) are not shown.
==22048== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==22048== 
==22048== For lists of detected and suppressed errors, rerun with: -s
==22048== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Looking for problems in cf_check_dump.txt:
+ check_valgrind_output cf_check_dump.txt
+ set -e
+ '[' '!' -f cf_check_dump.txt ']'
+ echo 'Looking for problems in cf_check_dump.txt:'
+ grep -i 'ERROR SUMMARY: 0 errors' cf_check_dump.txt
==22048== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
+ cat cf_check_dump.txt
+ sed -e '/ 0 errors/d' -e '/and suppressed error/d' -e '/a memory error detector/d'
+ no_errors filtered.txt
+ set +e
+ grep -i error filtered.txt
Error: This database contains unknown binary data - use --simple to print anyway
+ grep -q -i error filtered.txt
+ exit 1
+ echo 'FAIL: valgrind check failed'
FAIL: valgrind check failed
+ failure=1
+ exit 1
++ echo FAILURE
FAILURE
+ status=failure
```

**Comment by nickanderson** [comment]
@gpiero never mind, I will just pull that commit in here and add it to the existing ticket, but if you have some more changes queued up, it would be best to get them in separate PRs and associated with separate tickets.

**Comment by nickanderson** [comment]
@cf-bottom  shall we give jenkins another go? Nothing different in core still, so no reason to believe the valgrind check result will change except that in  another PR it didn't fail

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6324/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6324/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6324/

**Comment by nickanderson** [comment]
@cf-bottom let's try jenkins agin, but this time with the additonal PR to handle the bogus valgrind failure.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6331/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6331/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6331/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6338/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6338/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6338/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6340/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6340/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6340/

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Comment by vpodzime** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6345/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6345/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6345/

**Comment by nickanderson** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6376/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6376/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6376/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

heres hoping for greener skies.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6418/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6418/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6418/

**Review by olehermanse — APPROVED** [review]

**Comment by vpodzime** [comment]
> Sure, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/6418/)
> 
> **Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6418/

Looks practically green to me. :+1: @nickanderson feel free to merge this.

**Comment by nickanderson** [comment]
@gpiero , sorry for the very long delay here.

I rebased against master and hope to get this merged soon.

**Comment by nickanderson** [comment]
@gpiero, merged to master, backporting to 3.18, thanks for your first contribution! :partying_face:

**Pull request merged**
