### PR TITLE
ENT-8338: Started inventorying currently mounted file system types and mount points

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@jenkins, with exotics

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9190/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9190/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9190/

**Comment by nickanderson** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9199/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9199/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9199/

**Review by craigcomstock — APPROVED** [review]
looks good nick!

**Comment by nickanderson** [comment]
@olehermanse shall I merge or yank this out from MPF all together and put it into a build module? FWIW, my initial thought was the latter but in the ticket @vpodzime suggested doing in MPF.

**Comment by vpodzime** [comment]
> FWIW, my initial thought was the latter but in the ticket @vpodzime suggested doing in MPF.

I still think it's part of the basic system discovery and information.

**Comment by nickanderson** [comment]
> > FWIW, my initial thought was the latter but in the ticket @vpodzime suggested doing in MPF.
> 
> I still think it's part of the basic system discovery and information.

Yeah, it's just that it can easily blow up inventory.

Inventorying mount points:

```
root@demohub:~# awk '{print $2}' /etc/mtab 
/sys
/proc
/dev
/dev/pts
/run
/
/sys/kernel/security
/dev/shm
/run/lock
/sys/fs/cgroup
/sys/fs/pstore
/sys/fs/bpf
/proc/sys/fs/binfmt_misc
/dev/hugepages
/dev/mqueue
/sys/kernel/debug
/sys/kernel/tracing
/sys/kernel/config
/sys/fs/fuse/connections
/run/credentials/systemd-sysusers.service
/snap/core20/1623
/snap/lxd/23541
/boot/efi
/run/snapd/ns
/snap/snapd/17883
/proc/sys/fs/binfmt_misc
/snap/core20/1778
/snap/snapd/17950
/snap/lxd/24322
/run/snapd/ns/lxd.mnt
/run/user/0
root@demohub:~# awk '{print $2}' /etc/mtab  | wc -l
31
```
And some of those (notably the snap related ones) would be different on different hosts.

```
nickanderson@precision-5570:~/vagrant/cfengine/3.21.0-1$ awk '{print $2}' /etc/mtab
/sys
/proc
/dev
/dev/pts
/run
/
/sys/kernel/security
/dev/shm
/run/lock
/sys/fs/cgroup
/sys/fs/pstore
/sys/firmware/efi/efivars
/sys/fs/bpf
/proc/sys/fs/binfmt_misc
/dev/hugepages
/dev/mqueue
/sys/kernel/debug
/sys/kernel/tracing
/sys/fs/fuse/connections
/sys/kernel/config
/run/credentials/systemd-sysusers.service
/proc/fs/nfsd
/snap/0ad/588
/snap/0ad/592
/snap/bare/5
/snap/core18/2667
/snap/core20/1738
/snap/core20/1778
/snap/gnome-3-28-1804/161
/snap/gnome-3-38-2004/115
/snap/gnome-3-38-2004/119
/snap/gtk-common-themes/1534
/snap/gtk-common-themes/1535
/snap/kde-frameworks-5-98-qt-5-15-6-core20/9
/snap/krdc/64
/snap/sengi/37
/snap/snapd/17950
/snap/snapd/17883
/snap/thedesk/1272
/boot
/boot/efi
/run/qemu
/proc/sys/fs/binfmt_misc
/run/rpc_pipefs
/sys/fs/cgroup/net_cls
/net
/run/user/1000
/run/user/1000/doc
/snap/core18/2679
nickanderson@precision-5570:~/vagrant/cfengine/3.21.0-1$ awk '{print $2}' /etc/mtab | wc -l
49

```

**Comment by nickanderson** [comment]
I could have a filter on it, but I dunno what a good default filter would be.

```
nickanderson@precision-5570:~/vagrant/cfengine/3.21.0-1$ awk '{print $2}' /etc/mtab | grep -vP "^/(snap|boot|dev|sys|proc|run|$)"
/net

```

**Comment by vpodzime** [comment]
> Yeah, it's just that it can easily blow up inventory.

Oh, right. Well, let's focus on having inventory UI that can handle more items nicely ASAP then. But I guess, until then, this would cause more issues than benefits.

**Comment by nickanderson** [comment]
So, do you now think it's better as a module from build?

**Comment by vpodzime** [comment]
> So, do you now think it's better as a module from build?

Or part of MPF, but not enabled by default.

**Comment by olehermanse** [comment]
> Oh, right. Well, let's focus on having inventory UI that can handle more items nicely ASAP then. But I guess, until then, this would cause more issues than benefits.

@vpodzime https://tracker.mender.io/browse/ENT-7680

**Pull request merged**
