### PR TITLE
CFE-3628 Move bash and python CPT libraries and tests from core

### PR DESCRIPTION
**Pull request by Lex-2008**
merge together:
https://github.com/cfengine/core/pull/4771

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @nickanderson can review this?

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @nickanderson can review this?

**Comment by Lex-2008** [comment]
@nickanderson : Travis is :green_circle: - so let's :eyes: and merge?

**Comment by olehermanse** [comment]
@Lex-2008 jenkins?

**Comment by Lex-2008** [comment]
good point! @cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7091/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7091/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7091/

**Comment by Lex-2008** [comment]
Jenkins is :green_apple: enough

**Pull request merged**
