### PR TITLE
factor out current version to variable to make upgrading less error-prone (3.6.x)

### PR DESCRIPTION
**Pull request by estenberg**

### CODE REVIEW

**Comment by estenberg** [comment]
@nickanderson review please?

**Comment by estenberg** [comment]
Please merge this and #405 at the same time.

**Comment by nickanderson** [comment]
Shouldn't we set current_package_build or something too in order to handle The .0 and -1 packages.

**Comment by estenberg** [comment]
I don't think we change this very often (or shouldn't at least). But perhaps someone else has input?

**Comment by nickanderson** [comment]
We do not change it very often. Only if we have a packaging problem, which we have had in the past. 
We can skip it for now since its generally not used.

**Pull request merged**
