### PR TITLE
ENT-3602: execute runalerts.php as cfapache, to be identical to systemd_supervised systems.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson please review and merge. Which host should we test it in? Which hub platform is non-systemd supervised?

**Comment by nickanderson** [comment]
Centos 6 doesn't use systemd. Ubuntu 14 I think, Unsure about debian 7

**Comment by jimis** [comment]
Thanks @nickanderson, done.

**Comment by nickanderson** [comment]
Ok are we waiting for a build, or can we merge this now?

**Pull request merged**
