### PR TITLE
Remove log rotation for cf_notkept.log and cf_repaierd.log from 3.7 l…

### PR DESCRIPTION
**Pull request by maciejmrowiec**
…ib as their generation is removed.

### CODE REVIEW

**Comment by nickanderson** [comment]
They are not generated at all any longer? I thought it was tunable.

Should we still tidy up those old log files though? They will be there after an upgrade form 3.6 to 3.7.

**Comment by maciejmrowiec** [comment]
There are PR's in core/ent to remove those.
RIght, forgot about the leftovers :/:/ If we ignore this, will be get notkept every time it want's to do some cleanup? (how often?)

**Comment by nickanderson** [comment]
Is it really not kept if the file isn't found?

Its perfectly fine to leave leftovers, but I think we should document the fact they are left overs. Can you add this in the CHANGELOG rotation for these files was removed, it is safe to purge the left over files if desired.

**Comment by maciejmrowiec** [comment]
tested, it's: kept
I'd rather do not keep unmanaged leftovers so I'll keep that cleanup for now.

**Pull request closed without merging**
