### PR TITLE
CFE-2605: Available upgrade parsing is incorrect with some packages with apt_get module

### PR DESCRIPTION
**Pull request by amousset**

### CODE REVIEW

**Comment by kacf** [comment]
I suspect that the regex can be shortened even further. I'll take a look at this tomorrow.

**Comment by kacf** [comment]
Superseded by #899. @amousset: Can you verify that this works for you?

**Comment by amousset** [comment]
@kacf It works for me 👍

**Comment by kacf** [comment]
Thanks for testing, I have merged #899.

**Pull request closed without merging**
