### PR TITLE
Made the_great_package_test include def.cf

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2434/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2434/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2434/

**Comment by olehermanse** [comment]
@cf-bottom let's do another jenkins :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2435/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2435/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2435/

**Comment by olehermanse** [comment]
Cherry-pick:
https://github.com/cfengine/masterfiles/pull/1477

**Pull request merged**
