### PR TITLE
Add 3.7.7 changelog

### PR DESCRIPTION
**Pull request by Lex-2008**
Changelog: none

Signed-off-by: Aleksei Shpakovskii <aleksei.shpakovskii@cfengine.com>

### CODE REVIEW

**Comment by nickanderson** [comment]
it failed travis? its just a changelog

**Comment by olehermanse** [comment]
@nickanderson The failure is likely my fault, I'm merging cherry-picks

**Comment by Lex-2008** [comment]
ok, then we just need to restart the job after cherry-picks complete (and also update the changelogs :) )

**Comment by olehermanse** [comment]
@nickanderson @Lex-2008 Restarted this job. I'm not done cherrypicking, but branches should be in a good state now.

**Comment by olehermanse** [comment]
Green now.

**Comment by nickanderson** [comment]
Done with cherries here?

**Comment by olehermanse** [comment]
@nickanderson I think you should do cherry-picks for masterfiles? I'm not done with C repos, no.

**Comment by nickanderson** [comment]
I cherry pick MPF changes as I go, no need to worry too much about MPF backports.

**Comment by nickanderson** [comment]
Yep looks OK

**Pull request merged**
