### PR TITLE
ENT-4628: Could not look up name 'root' (LookupAccountName)

### PR DESCRIPTION
**Pull request by craigcomstock**
The "Permissions and Ownership" policy is only suitable for UNIX systems.

Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@nickanderson I think this is a regression bug from 3.12.1 to 3.12.2 due to this change: https://github.com/cfengine/masterfiles/commit/fd1c087d34d0ecda6edeef9367bf6bcb1b7053dc#diff-9ffaada4178b3e20aa450e4ac374cbe1R74

Please review/improve my fix which I have tested and it achieves the goal of not having errors. This change does not of course address the bigger issue of enforcing permissions and ownership on windows systems.

**Comment by craigcomstock** [comment]
Will need this in 3.12.x

**Comment by nickanderson** [comment]
This should be picked as well, I will take care of it.

**Comment by olehermanse** [comment]
Cherry-picks: 
https://github.com/cfengine/masterfiles/pull/1396
https://github.com/cfengine/masterfiles/pull/1397

**Pull request merged**
