### PR TITLE
ENT-8936: Added fallback to top-level feeder dump directory

### PR DESCRIPTION
**Pull request by craigcomstock**
This change makes it possible for a superhub 3.18.3 and newer to pull dumps from 3.18.2 and older feeders.

Ticket: ENT-8936
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8628/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8628/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8628/

**Comment by craigcomstock** [comment]
Failed unstable on mingw, problems saving artifacts to buildcache: https://tracker.mender.io/browse/ENT-9200, will try again tomorrow.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8634/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8634/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8634/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8647/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8647/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8647/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks :)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins, last build failed due to missing config in mingw build host.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8657/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8657/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8657/

**Comment by craigcomstock** [comment]
only failed php/selenium tests so good to go I think.

**Review by nickanderson — APPROVED** [review]

**Comment by craigcomstock** [comment]
cherry pick to 3.18.x only: https://github.com/cfengine/masterfiles/pull/2510

**Pull request merged**
