### PR TITLE
ENT-7446: Added self upgrade support for suse (3.18)

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6900/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6900/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6900/

**Comment by nickanderson** [comment]
@cf-bottom  jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6907/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6907/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6907/

**Pull request merged**
