### PR TITLE
ENT-8524: Stopped loading Apache mod_filter and mod_ext_filter by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1028

We do not use the features provided by these modules, so we should not load them by default.

Ticket: ENT-8524
Changelog: Title

### CODE REVIEW

**Review by Lex-2008 — APPROVED** [review]

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7867/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7867/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7867/

**Comment by nickanderson** [comment]
@aleksandrychev this build failed the php selenium tests

https://ci.cfengine.com/job/testing-run-php-selenium-tests/3495/

Is this a legitimate failure? When I looked through our Apache config I didn't see that we were using any of the directives from the mod_filter and mod_ext_filter modules.

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7872/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7872/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7872/

**Comment by aleksandrychev** [comment]
I re-run failed job

[Build Status](https://ci.cfengine.com/job/testing-run-php-selenium-tests/3499/)

**Comment by olehermanse** [comment]
@cf-bottom jenkins again, please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7875/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7875/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7875/

**Pull request merged**
