### PR TITLE
ENT-6840/master: Work around deployment test failure

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6174/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6174/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6174/

**Review by craigcomstock — APPROVED** [review]
This change seems to work for me. It may not be perfect but I think it is a good idea to help our CI be more green.

**Comment by nickanderson** [comment]
> This change seems to work for me. It may not be perfect but I think it is a good idea to help our CI be more green.

The jenkins build failed with the same errors though. See https://ci.cfengine.com/job/fr-tests/2326/testReport/junit/(root)/new_tests_FR_tests_all_platforms_/FR_basic_setup_test/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6182/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6182/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6182/

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Pull request merged**
