### PR TITLE
ENT-5420: Added use of services promise for FR postgresql reconfig in case of systemd

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4873/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4873/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4873/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4888/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4888/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4888/

**Comment by craigcomstock** [comment]
@nickanderson this one should probably get in sooner than later. :) Thanks!

**Comment by craigcomstock** [comment]
Since this was a cherry-pick already approved and in master I went ahead and merged.

**Pull request merged**
