### PR TITLE
Add: Classes body tailored for use with diff

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
@bronto @tzz

**Comment by tzz** [comment]
I love it. I would pass a scope parameter through, though.

**Comment by nickanderson** [comment]
you mean diff_results(scope, x)

**Comment by tzz** [comment]
Yes, exactly. I wish there was a way to default body parameters! But lacking that, yeah, let the user specify it.

**Pull request merged**
