### PR TITLE
Vacuum job port.

### PR DESCRIPTION
**Pull request by maciejmrowiec**

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
passes cf-promises on 3.6 / 3.5

**Comment by jimis** [comment]
This should be the last piece missing from 3.6.6.

@nickanderson I'll leave reviewing, merging to you! :-)

**Comment by nickanderson** [comment]
Changelog entry needed for this?

**Comment by nickanderson** [comment]
nevermind, we dont have a masterfiles changelog in 3.6.x

**Pull request merged**
