### PR TITLE
ENT-7233: Added cleanup of database and status semaphore when federation target_state is off (3.15)

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: ENT-7233
Changelog: Title
(cherry picked from commit 15add8d20540bfb092088fa0f8197455c31977ad)

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6929/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6929/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6929/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6931/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6931/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6931/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
