### PR TITLE
CFE-2920: Made internal bundle common to avoid errors in daemons

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins.

**Comment by olehermanse** [comment]
@nickanderson afaict, this needs to be backported, at least to 3.12.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1357/)

https://ci.cfengine.com/job/pr-pipeline/1357/

**Comment by olehermanse** [comment]
@nickanderson fixed.

**Comment by olehermanse** [comment]
Cherry-picked here: https://github.com/cfengine/masterfiles/pull/1207

**Pull request merged**
