### PR TITLE
CFE-2875 Store epoch for packages managed by zypper module 3.12.x

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom  you are lazy

[Build Status](https://ci.cfengine.com/job/pr-pipeline/1009/)

**Pull request merged**
