### PR TITLE
CFE-2609: lib/event.cf: add event handling framework

### PR DESCRIPTION
**Pull request by tzz**
@nickanderson similar to `testing.cf`

@yann-soubeyrand maybe this is useful regarding your questions about event handling...

### CODE REVIEW

**Comment by tzz** [comment]
@yann-soubeyrand updated with event persistence as discussed

**Comment by nickanderson** [comment]
@tzz can i haz a test for this?

**Comment by tzz** [comment]
I was waiting for a review of the API. Does the library look reasonable?

**Comment by nickanderson** [comment]
I think it seems reasonable, it reminds me very much of the [feature bundles](https://github.com/cfengine/masterfiles/blob/master/lib/feature.cf)

**Pull request merged**
