### PR TITLE
Fix for CFE-2445

### PR DESCRIPTION
**Pull request by ageorgop**
Not sure about style but this fixes the issue.  Let me know if you need me to adjust it.

### CODE REVIEW

**Comment by kacf** [comment]
Nice! Looks good to me in principle, but need to wait for Jenkins to be back up to test this.

**Comment by ageorgop** [comment]
I had a feeling about issue 1 after I submitted the PR.  Now for 2 I will try and think of a cleaner way to do this.

**Comment by kacf** [comment]
Thanks, @ageorgop!

**Comment by kacf** [comment]
I haven't looked at this in a while. Has there been any luck in resolving point 2? From looking at it, it seems like stdin is still occupied by the pipe that feeds the script.

**Pull request closed without merging**
