### PR TITLE
CFE-3630: Suppressed output redirection for aix watchdog cronjob (master)

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6466/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6466/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6466/

**Comment by nickanderson** [comment]
@cf-bottom, I think the test failure is bunk. Please ask jenkins to try again.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6469/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6469/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6469/

**Comment by nickanderson** [comment]
@cf-bottom, I think the test failure is bunk. Please ask jenkins to try again.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6475/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6475/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6475/

**Comment by nickanderson** [comment]
@craigcomstock this test seems to be failing because of something completely unrelated.

```
52.48.16.212	  notice: Q: ".../cf-agent" -f /":    error: Could not open database txn /var/cfengine/state/cf_state.lmdb: Invalid argument
```
Can you confirm this simple change should not be blocked by that test failure? (note, PRs to backport this to 3.15 and 3.12 are green)

**Comment by olehermanse** [comment]
@nickanderson that is a separate issue tracked here:

https://tracker.mender.io/browse/ENT-6527

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
