### PR TITLE
ENT-8066 Fixed windows self upgrade script for Windows 2008

### PR DESCRIPTION
**Pull request by craigcomstock**
For versions before Windows 2012 we need an extra set of
quotes around the script path otherwise the path is chopped
at the first space: "C:\Program".

Ticket: ENT-8066
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins packages please, thanks :)

**Review by nickanderson — APPROVED** [review]
I don't understand how why the double double quotes work for this

**Comment by larsewi** [comment]
Tried this on Windows Server 2008. Did not work for me 😢 
```
Administrator@WIN-NTO7O3L97A9 C:\Program Files\Cfengine>bin\cf-agent.exe -KIf "C:\Program Files\Cfen
gine\inputs\standalone_self_upgrade.cf"
R: Ensuring local software cache in C:\Program Files\Cfengine\software_updates\windows_x86_64 is up 
to date
    info: Executing 'no timeout' ... '\schedule_unattended_upgrade.ps1'
   error: Finished command related to promiser '\schedule_unattended_upgrade.ps1' -- an error occurr
ed, returned 1
  notice: Q: "...pgrade.ps1": \schedule_unattended_upgrade.ps1 : File C:\schedule_unattended_upgrade
.ps1 cannot be loaded. The 
Q: "...pgrade.ps1": file C:\schedule_unattended_upgrade.ps1 is not digitally signed. The script will
 not execute on 
Q: "...pgrade.ps1": the system. For more information, see about_Execution_Policies at 
Q: "...pgrade.ps1": http://go.microsoft.com/fwlink/?LinkID=135170.
Q: "...pgrade.ps1": At line:1 char:1
Q: "...pgrade.ps1": + \schedule_unattended_upgrade.ps1
Q: "...pgrade.ps1": + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Q: "...pgrade.ps1":     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
Q: "...pgrade.ps1":     + FullyQualifiedErrorId : UnauthorizedAccess
    info: Last 9 quoted lines were generated by promiser '\schedule_unattended_upgrade.ps1'
    info: Completed execution of '\schedule_unattended_upgrade.ps1'
   error: Method 'windows_unattended_upgrade' failed in some repairs
   error: Method 'cfengine_software_version' failed in some repairs
R: Running C:\Program Files\Cfengine\inputs\standalone_self_upgrade.cf
```

**Comment by larsewi** [comment]
Tried this on Windows Server 2008. Did not work for me 😢 
```
R: Ensuring local software cache in C:\Program Files\Cfengine\software_updates\windows_x86_64 is up 
to date
    info: Executing 'no timeout' ... '\schedule_unattended_upgrade.ps1'
  notice: Q: "...pgrade.ps1": ERROR: Invalid argument/option - 'Files\Cfengine\bin\unattended-upgrad
e.bat'.
Q: "...pgrade.ps1": Type "SCHTASKS /CREATE /?" for usage.
    info: Last 2 quoted lines were generated by promiser '\schedule_unattended_upgrade.ps1'
    info: Completed execution of '\schedule_unattended_upgrade.ps1'
R: Running C:\Program Files\Cfengine\inputs\standalone_self_upgrade.cf
```

**Comment by nickanderson** [comment]
> Tried this on Windows Server 2008. Did not work for me cry
> 
> ```
> R: Ensuring local software cache in C:\Program Files\Cfengine\software_updates\windows_x86_64 is up 
> to date
>     info: Executing 'no timeout' ... '\schedule_unattended_upgrade.ps1'
>   notice: Q: "...pgrade.ps1": ERROR: Invalid argument/option - 'Files\Cfengine\bin\unattended-upgrad
> e.bat'.
> Q: "...pgrade.ps1": Type "SCHTASKS /CREATE /?" for usage.
>     info: Last 2 quoted lines were generated by promiser '\schedule_unattended_upgrade.ps1'
>     info: Completed execution of '\schedule_unattended_upgrade.ps1'
> R: Running C:\Program Files\Cfengine\inputs\standalone_self_upgrade.cf
> ```

Confirmed, that didn't do the job. We have another PR up with a slightly different change that does seem to work.

**Pull request closed without merging**
