### PR TITLE
Package module too verbose redmine7485

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@kacf please review

The problem with the quick solution that I implemented is that it always suppresses `stdout` of subcommands, and sometimes you get an error on `stderr` and you can't find out what caused it:
```
[root@localhost ~]# /var/cfengine/bin/cf-agent -KIf ./redmine7485-pack.cf
   error: Error installing package 'vim'
```

The ideal solution would be to redirect stdout always, and have our C code log `stdout` with DEBUG or VERBOSE level, while `stderr` is logged at ERR level. But that change is way more complex and the ticket needs to be re-estimated if we follow that approach.

**Comment by kacf** [comment]
Looks good to me!

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by jimis** [comment]
All green. @kacf quick question before merging: the way I've coded it required python 2.4 (because of os.devnull), is that OK?

**Comment by kacf** [comment]
That's fine, the latest one is 2.7.

**Comment by jimis** [comment]
Thanks, merging and cherry-picking down to 3.8.2 and 3.7.3.

**Pull request merged**
