### PR TITLE
ENT-3283: copy test_package_module_apt_get file from master 

### PR DESCRIPTION
**Pull request by Lex-2008**
I completely reworked the commit - now it's just plain file copy, no fancy cherry-picking or merge conflict resolution

### CODE REVIEW

**Comment by jimis** [comment]
Is this a cherry-pick? If so use `-x` switch when cherry-picking. The contents are for @nickanderson to review.

**Comment by Lex-2008** [comment]
git help says that "-x" works only for cherry picks without conflicts, so i've added relevant info manually

**Comment by nickanderson** [comment]
The content looks really different from what is in master. Since nothing in the protocol has changed, to me it makes sense that the modules in maintained branches match what is in master.

**Comment by Lex-2008** [comment]
hm, then let's copy just tests/unit/test_package_module_apt_get file and see if it helps!

**Comment by nickanderson** [comment]
That's what I would probably do. I can't think of any current reason why we wouldnt want the package modules to be the same across all the maintained branches.

**Comment by Lex-2008** [comment]
ok, the PR updated - now it's just file copy :)

**Comment by nickanderson** [comment]
It passed travis testing, so merging.

**Pull request merged**
