### PR TITLE
ENT-8554: Stopped loading unused Apache modules on Enterprise Hubs by default

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8458/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8458/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8458/

**Comment by craigcomstock** [comment]
sequential-tests failed due to flaky ssh: 

```
ssh_exchange_identification: read: Connection reset by peer
lost connection
```

suse and debian11arm are known issues. I'd say OK to this one!

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
