### PR TITLE
Disabled federation policy test to see if great package test is passing

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by craigcomstock** [comment]
Try this change along with https://github.com/cfengine/core/pull/3762 in jenkins:
https://ci.cfengine.com/job/pr-pipeline/2423/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2424/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2424/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2424/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2429/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2429/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2429/

**Pull request merged**
