### PR TITLE
Change: Tag default ipv4 gateway interface for inventory

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Inventory of default ipv4 gateway interface when
class cfengine_internal_inventory_dgw_ipv4_iface is defined

### CODE REVIEW

**Comment by nickanderson** [comment]
@estenberg I did it like this so that it's easy to augment the mission portal inventory, not something that everyone would want but this allows it to be turned on by just setting a class. Thoughts?

**Comment by nickanderson** [comment]
ping @estenberg

**Comment by estenberg** [comment]
Agree, looks useful and doesn't change that often; so fits within scope of inventory.

However, this is already implemented in C and tagged as part of #2245 (look for default_gateway) so I think we should wait and see what happens with that pull request and close this one if it goes in.

**Comment by nickanderson** [comment]
@tzz @estenberg with the new proc parsing for linux network information is the default gw interface already tagged? If so then I don't think we need this.

**Comment by nickanderson** [comment]
This PR seems to have gotten messed up anyhow

**Comment by nickanderson** [comment]
those commits apper to already be in master from #679

**Pull request closed without merging**
