### PR TITLE
CFE-2875 Store epoch for packages managed by zypper module 3.10.x

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
lazy bot [Build Status](https://ci.cfengine.com/job/pr-pipeline/1009/)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1010/)

https://ci.cfengine.com/job/pr-pipeline/1010/

**Comment by nickanderson** [comment]
Failure on Debian is unrelated to this change.

**Pull request merged**
