### PR TITLE
ENT-6071 Refactor package module options parsing to shared code

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5344/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5344/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5344/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins another time please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5345/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5345/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5345/

**Comment by craigcomstock** [comment]
@cf-bottom thanks for all the help with jenkins, another time thanks

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5346/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5346/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5346/

**Comment by craigcomstock** [comment]
this refactor is not worth the effort I think, closing for now

**Pull request closed without merging**
