### PR TITLE
Add body package_method apt_get_safe 

### PR DESCRIPTION
**Pull request by brontolinux**
This package method use more "prudential" options for apt/dpkg to reduce the likeliness of unexpected upgrades/removals of packages.

### CODE REVIEW

**Comment by brontolinux** [comment]
Hei alle sammen :-) Is this going to be merged or not? I had nearly forgotten about it!

**Comment by estenberg** [comment]
Can we just take it as part of the apt_get body for 3.7 instead of new body please?
Too many dead bodies already. :)

**Comment by brontolinux** [comment]
@estenberg : I am not sure it is appropriate for generic use, just look at the options used with apt and you'll probably agree... I'm not going to fight over this anyway, the product is yours, I must know what's appropriate for CFEngine better than anyone.

**Comment by kacfengine** [comment]
I agree that we should favor finding ways to fix the default package body rather than adding a new one, so I'll close this for now.

**Pull request closed without merging**
