### PR TITLE
ENT-8608: Stopped loading Apache mod_auth_digest by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1060

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7948/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7948/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7948/

**Comment by nickanderson** [comment]
Failed selenium tests: https://ci.cfengine.com/job/testing-run-php-selenium-tests/3609/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7986/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7986/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7986/

**Comment by craigcomstock** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/7986/)
> 
> **Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7986/
> 
> **Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7986/

@vpodzime @Lex-2008 @nickanderson is this centos 7 hub pre scriptlet failure related to out of space on a build machine? https://tracker.mender.io/browse/ENT-5307 I noticed the ticket is closed quite a while ago and the exit code was 123 in the ticket's case but 1 in this case. Also, this is a DT result so not on that particular build machine. New ticket then?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8037/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8037/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8037/

**Comment by vpodzime** [comment]
Needs a rebase of cfengine/buildscripts#1060 (https://github.com/cfengine/buildscripts/pull/1060#issuecomment-1147306618)

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by nickanderson** [comment]
> Needs a rebase of [cfengine/buildscripts#1060](https://github.com/cfengine/buildscripts/pull/1060) ([cfengine/buildscripts#1060 (comment)](https://github.com/cfengine/buildscripts/pull/1060#issuecomment-1147306618))

rebased.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8040/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8040/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8040/

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
