### PR TITLE
ENT-5051: Added policy to revert changes when target_state is off (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins dude

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4202/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4202/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4202/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4206/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4206/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4206/

**Comment by craigcomstock** [comment]
jenkins failing on known-broken tests

```
    tests/all_packages/test_restarting_hub_agents.py.PACKAGES_HUB_x86_64_linux_debian_7,ubuntu-12-04-x64
    tests/all_packages/test_restarting_hub_agents.py.PACKAGES_HUB_x86_64_linux_debian_7,ubuntu-14-04-x64
```

**Pull request merged**
