### PR TITLE
ENT-10962: Fixed mission portal restoring changes from /var/cfengine/share/GUI

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]
sweet.

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10154/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10154/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10154/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10184/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10184/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10184/

**Comment by craigcomstock** [comment]
sequential-test failed due to missing cf-support not being able to process core dumps on ubuntu 20 apparently. I will fix in ENT-11106.

**Comment by craigcomstock** [comment]
acceptance-test problem here was a publishing error for release-data which was fixed last week so I have re-run that job here.

**Comment by craigcomstock** [comment]
The no-noise failure in sequential-tests maybe is a flake with aws ubuntu repos not being available? Logged a ticket: ENT-11107

So I think your PR is good to go.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10255/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10255/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10255/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10264/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10264/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10264/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10268/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10268/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10268/

**Comment by craigcomstock** [comment]
made a ticket for your sequential-tests failure, maybe it is a flake? https://northerntech.atlassian.net/browse/ENT-11182

**Comment by craigcomstock** [comment]
trying sequential-tests again, we'll see if the build packages are still available to use
[Build Status](https://ci.cfengine.com/job/sequential-tests/6663/)

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10321/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10321/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10321/

**Comment by nickanderson** [comment]
@craigcomstock this is failing FR distributed cleanup and bootstrap tests, should we go ahead and merged (I know you already approved but I don't want to make new CI problems.

Bootstrap failed in relation to log permission change:

```
20:04:25 Permission or ownership changes in normal agent run!
20:04:25 + grep -Pi 'info: (Group of|Owner of|.*had permission)' .25595.normal.log
20:04:25 34.240.57.64	    info: Regular file '/var/cfengine/httpd/logs/application/./log-2024-01-25.log' had permissions 0644, changed it to 0600
20:04:25 + fail_test 1
20:04:25 + failure
```

And FR maybe had issues with SSH?

```
20:13:52 Q: ".../bin/bash /opt/": 18.201.124.65
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] Trying fallback dump directory /opt/cfengine/federation//cftransport/source. Upgrade masterfiles on feeder to enable multiple superhubs pulling from one feeder.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] Trying fallback dump directory /opt/cfengine/federation//cftransport/source. Upgrade masterfiles on feeder to enable multiple superhubs pulling from one feeder.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] Trying fallback dump directory /opt/cfengine/federation//cftransport/source. Upgrade masterfiles on feeder to enable multiple superhubs pulling from one feeder.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] Trying fallback dump directory /opt/cfengine/federation//cftransport/source. Upgrade masterfiles on feeder to enable multiple superhubs pulling from one feeder.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] No files to transport.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] No files to transport.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] No files to transport.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] No files to transport.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
20:13:52 Q: ".../bin/bash /opt/": [Thu Jan 25 02:13:52 UTC 2024] Trying fallback dump directory /opt/cfengine/federation//cftransport/source. Upgrade masterfiles on feeder to enable multiple superhubs pulling from one feeder.
20:13:52 Q: ".../bin/bash /opt/": Permission denied (publickey).
```

**Comment by craigcomstock** [comment]
- distributed cleanup ssl failure is known https://northerntech.atlassian.net/browse/ENT-11215
- cf-support timeout after failure is known https://northerntech.atlassian.net/browse/ENT-10486

seems you could go ahead and merge 👍

**Pull request merged**
