### PR TITLE
CFE-2460: Add ability to append to bundlesequnece with def.json

### PR DESCRIPTION
**Pull request by nickanderson**
Changelog: Title

### CODE REVIEW

**Comment by tzz** [comment]
YES for me. Maybe implementing this in C makes sense, and the setting name is really long, but I like it.

**Comment by nickanderson** [comment]
@jimis this seems like a regression in core. Note that LTS passes, while master fails. I might be able to do some policy acrobatics to get around this, but I would rather not do acrobatics when it looks like a regression.

**Comment by jimis** [comment]
Travis is failing this pull request with CFEngine 3.9.1, if this is a bug in Core it should be fixed there first. Else all Travis builds will keep coming red.

**Comment by nickanderson** [comment]
@tzz Yeah the name is long. But it follows a pattern, and works with 3.7+. I just kept running into issues when I was trying to use a data container as suggested in #730

**Comment by nickanderson** [comment]
rebased

**Pull request merged**
