### PR TITLE
ENT-6966 Re-enabled *-list-cached tests

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-6966
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics, why not! I never hang out with those folks any more. :(

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7210/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7210/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7210/

**Comment by craigcomstock** [comment]
@cf-bottom lets try jenkins again with exotics, enabled more tests, rewrote test_module as shell script to get around exotics not having easily predictable python path for a shebang.

**Comment by craigcomstock** [comment]
@cf-bottom lets try jenkins again with exotics, enabled more tests, rewrote test_module as shell script to get around exotics not having easily predictable python path for a shebang.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7276/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7276/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7276/

**Comment by craigcomstock** [comment]
Will retry ubuntu 20, might be a flake: ENT-7541

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7281/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7281/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7281/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics, sorry about that, been working them hard lately :O

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7293/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7293/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7293/

**Comment by craigcomstock** [comment]
This is looking good. Exotics passed except solaris.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7305/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7305/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7305/

**Comment by craigcomstock** [comment]
solaris retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/7307/)

**Comment by craigcomstock** [comment]
Another solaris retry, now that buildscripts deps stuff is patched up and should work. Also fixed `command -v ggrep` not outputing anything which probably broke things as well :o: 

[Build Status](https://ci.cfengine.com/job/pr-pipeline/7359/)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7361/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7361/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7361/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please, thanks.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7389/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7389/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7389/

**Comment by craigcomstock** [comment]
failures are

- ssh failed on solaris 11 during bootstrap-tests, restart, acceptable since those platforms are flaky
- suse 11 failed in local_updates_list_cached_cf, not sure why

I will investigate suse 11 failures soon.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7390/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7390/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7390/

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
All failures are known issues or flakes. Merging. :) Hold my 🍺

**Comment by craigcomstock** [comment]
cherry picks
https://github.com/cfengine/masterfiles/pull/2175 (3.15)
https://github.com/cfengine/masterfiles/pull/2176 (3.18)

**Pull request merged**
