### PR TITLE
master CI

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom please run this in jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2843/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2843/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2843/

**Comment by olehermanse** [comment]
@cf-bottom please start another jenkins build :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2845/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2845/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2845/

**Pull request closed without merging**
