### PR TITLE
CFE-3630: Fixes missing output redirection for aix watchdog cronjob (master)

### PR DESCRIPTION
**Pull request by flynn1973**

### CODE REVIEW

**Review by nickanderson — CHANGES_REQUESTED** [review]
Thanks @flynn1973 !

The change looks OK to me. Can you please amend the commit?

Subject: `Update watchdog.cf` -> `Suppressed output from watchdog on AIX to prevent the mail spool from filling up`

Body:

    Ticket: CFE-3630
    Changelog: Title

**Comment by flynn1973** [comment]
i tried to do it, but once again i messed up everything, the git workflow here is not my cup of tea i guess :-)

```
commit de40dadb05be41a1052b4724cec9bef8363c7e5c (HEAD -> master, origin/master, origin/HEAD)
Author: flynn1973 <christian.tremel@itsv.at>
Date:   Tue Apr 20 08:06:29 2021 +0200

    Revert "CFE-3630: Fixes missing output redirection for aix watchdog cronjob"

commit bab31eb90a11d47427477983723ae4333142effb
Author: flynn1973 <christian.tremel@itsv.at>
Date:   Mon Apr 19 14:16:56 2021 +0200

    Ticket: CFE-3630
    Changelog: Title

```

**Comment by nickanderson** [comment]
> i tried to do it, but once again i messed up everything, the git workflow here is not my cup of tea i guess :-)
> 
> edit:
> 
> ok, got it eventually, my fault, sorry for the ramblings.

Mmm, Now there are conflicts, I will take care of it but many thanks for trying.

I opened <https://github.com/cfengine/masterfiles/pull/1968> to supersede this pull request.

This is what I did.

    ╭─nickanderson@nickanderson-ThinkPad-W550s ~/CFEngine/masterfiles  ‹master› 
    ╰─➤  git remote                                                                                                   128 ↵
    Fdall
    Lex-2008
    aleksandrychev
    atsaloli
    basvandervlies
    craigcomstock
    flynn1973
    gpiero
    josephholsten
    mikeweilgart
    olehermanse
    oleorhagen
    origin
    systemheld
    tzz
    upstream
    vpodzime
    xaxo05
    ╭─nickanderson@nickanderson-ThinkPad-W550s ~/CFEngine/masterfiles  ‹master› 
    ╰─➤  git fetch flynn1973
    remote: Enumerating objects: 11, done.
    remote: Counting objects: 100% (11/11), done.
    remote: Compressing objects: 100% (9/9), done.
    remote: Total 11 (delta 2), reused 10 (delta 2), pack-reused 0
    Unpacking objects: 100% (11/11), 3.40 KiB | 347.00 KiB/s, done.
    From https://github.com/flynn1973/masterfiles
     * [new branch]          CFE-3630-Fixes-missing-output-redirection-for-aix-watchdog-cronjob -> flynn1973/CFE-3630-Fixes-missing-output-redirection-for-aix-watchdog-cronjob
       97a053480..de40dadb0  master     -> flynn1973/master
    ╭─nickanderson@nickanderson-ThinkPad-W550s ~/CFEngine/masterfiles  ‹CFE-3630/master› 
    ╰─➤  git cherry-pick -x 3ab33ae8f450791bca412517b14b560b3fbce385
    *** Preserving this moment in history.
    *** Preserving this moment in history.
    *** Preserving this moment in history.
    [CFE-3630/master b6e48360a] Suppressed output from watchdog on AIX to prevent the mail spool from filling up
     Author: flynn1973 <christian.tremel@itsv.at>
     Date: Mon Apr 19 14:16:56 2021 +0200
     1 file changed, 1 insertion(+), 1 deletion(-)
    ╭─nickanderson@nickanderson-ThinkPad-W550s ~/CFEngine/masterfiles  ‹CFE-3630/master› 
    ╰─➤  git push origin CFE-3630/master                            
    Using GPG to open /home/nickanderson/.authinfo.gpg: [gpg --decrypt /home/nickanderson/.authinfo.gpg]
    gpg: encrypted with 4096-bit RSA key, ID F8D835C3D65EF27A, created 2013-05-01
          "Nick Anderson <nick@cmdln.org>"
    Enumerating objects: 11, done.
    Counting objects: 100% (11/11), done.
    Delta compression using up to 4 threads
    Compressing objects: 100% (6/6), done.
    Writing objects: 100% (6/6), 637 bytes | 637.00 KiB/s, done.
    Total 6 (delta 5), reused 0 (delta 0)
    remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
    remote: 
    remote: Create a pull request for 'CFE-3630/master' on GitHub by visiting:
    remote:      https://github.com/nickanderson/masterfiles/pull/new/CFE-3630/master
    remote: 
    To https://github.com/nickanderson/masterfiles
     * [new branch]          CFE-3630/master -> CFE-3630/master
    ╭─nickanderson@nickanderson-ThinkPad-W550s ~/CFEngine/masterfiles  ‹CFE-3630/master› 
    ╰─➤  gh pr create 
    ? Which should be the base repository (used for e.g. querying issues) for this directory? cfengine/masterfiles
    Warning: 1 uncommitted change
    ? Where should we push the 'CFE-3630/master' branch? nickanderson/masterfiles
    
    Creating pull request for nickanderson:CFE-3630/master into master in cfengine/masterfiles
    
    ? Title CFE-3630: Suppressed output redirection for aix watchdog cronjob (master)
    ? Body <Received>
    ? What's next? Submit
    Using GPG to open /home/nickanderson/.authinfo.gpg: [gpg --decrypt /home/nickanderson/.authinfo.gpg]
    gpg: encrypted with 4096-bit RSA key, ID F8D835C3D65EF27A, created 2013-05-01
          "Nick Anderson <nick@cmdln.org>"
    Branch 'CFE-3630/master' set up to track remote branch 'CFE-3630/master' from 'origin'.
    Everything up-to-date
    https://github.com/cfengine/masterfiles/pull/1968

**Comment by nickanderson** [comment]
Superseded by https://github.com/cfengine/masterfiles/pull/1968

**Pull request closed without merging**
