### PR TITLE
ENT-9601: Debug installed-list-cached test on debian 11 arm

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9601

### CODE REVIEW

**Comment by craigcomstock** [comment]
debug build: [Build Status](https://ci.cfengine.com/job/pr-pipeline/8922/)

**Comment by craigcomstock** [comment]
weird, first time `cat` was undefined, next time it was doubly defined, so define something entirely different: `catty`

retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/8927/)

**Comment by craigcomstock** [comment]
Seeing this pass CI makes me think that we can just keep these extra reports so we have insights when things fail.

retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/8938/)

**Review by nickanderson — APPROVED** [review]
aight

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9720/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9720/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9720/

**Pull request closed without merging**
