### PR TITLE
ENT-7465: Insured exported reports from Mission Portal are in the correct location

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-7465
Changelog: Title

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7064/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7064/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7064/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7065/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7065/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7065/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7071/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7071/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7071/

**Review by nickanderson — APPROVED** [review]

**Comment by nickanderson** [comment]
Do not believe the test failure is related to this change. Merging.

**Pull request merged**
