### PR TITLE
CFE-4375: Refactored extraction of home directory from parsing getent output to getuserinfo()

### PR DESCRIPTION
**Pull request by nickanderson**
Ticket: CFE-4375
Changelog: Title

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]
makes sense. so if getuserinfo() fails to get home_dir the commands promise will not actuate.

**Comment by flynn1973** [comment]
did a quick run...getent messages still showing up...

````
root@aixtest01: /root # tail -1000f /var/log/syslog/messages | grep getent
Apr 25 10:30:42 aixtest01 local7:err|error cf-agent[12255538]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)
Apr 25 10:30:42 aixtest01 local7:err|error cf-agent[12255540]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)
Apr 25 10:32:50 aixtest01 local7:err|error cf-agent[15794516]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)
Apr 25 10:32:50 aixtest01 local7:err|error cf-agent[15794518]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)
Apr 25 10:34:14 aixtest01 local7:err|error cf-agent[4063584]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)
Apr 25 10:34:14 aixtest01 local7:err|error cf-agent[4063586]: CFEngine(agent)  Couldn't run '/usr/bin/getent'. (execv: No such file or directory)

````

which is strange as there is no significant trace of it in masterfiles...
````
root@aixtest01: /var/cfengine/inputs # grep -r getent *
lib/paths.cf:      "path[getent]"        string => "/usr/bin/getent";

````

some weird caching somewhere?

**Comment by nickanderson** [comment]
@flynn1973 Cool, I will look closer there, Ive got an idea of whats causing it.

**Comment by nickanderson** [comment]
> @flynn1973 Cool, I will look closer there, Ive got an idea of whats causing it.

In paths.cf the `getent` path is only set for `linux`.

So, I don't think those are directly related to the policy. I think they are from this C code: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/unix.c#L251-L258

**Comment by nickanderson** [comment]
@flynn1973 what version of aix and what version of cfengine are you running?

**Comment by flynn1973** [comment]
> @flynn1973 what version of aix and what version of cfengine are you running?

3.21.4

**Comment by nickanderson** [comment]
Alright, I am going to merge this change to master for 3.24.0.

**Comment by flynn1973** [comment]
> > @flynn1973 Cool, I will look closer there, Ive got an idea of whats causing it.
> 
> In paths.cf the `getent` path is only set for `linux`.
> 
> So, I don't think those are directly related to the policy. I think they are from this C code: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/unix.c#L251-L258

hmm...i can't see a related log statement in libpromises/unix.c...

**Comment by nickanderson** [comment]
> hmm...i can't see a related log statement in libpromises/unix.c...

I think it's from here: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/pipes_unix.c#L412-L414

or: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/pipes_unix.c#L542-L545

**Comment by flynn1973** [comment]
> > hmm...i can't see a related log statement in libpromises/unix.c...
> 
> I think it's from here: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/pipes_unix.c#L412-L414
> 
> or: https://github.com/cfengine/core/blob/c5d960f2614f0990e81e6ed8cd4e1b321cc44e07/libpromises/pipes_unix.c#L542-L545

just checked the same file...yep...

**Comment by nickanderson** [comment]
@flynn1973 You haven't always had those errors on aix, do you know when they appeared? Curious what the change was that removed getent from the system, or perhaps changed it from where we expect to find it.

**Pull request merged**
