### PR TITLE
ENT-4050 Remove design center support

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
cf-bottom jenkins, please

**Comment by nickanderson** [comment]
@cf-bottom  jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1098/)

https://ci.cfengine.com/job/pr-pipeline/1098/

**Pull request merged**
