### PR TITLE
Add pkgsrc package module. See http://www.pkgsrc.org/

### PR DESCRIPTION
**Pull request by bahamat**
This module primarily supports NetBSD and SmartOS. By extension, it supports any platform that pkgsrc itself supports.

### CODE REVIEW

**Comment by nickanderson** [comment]
Awesome! Can you provide a test with this?

**Comment by nickanderson** [comment]
ping @kacfengine @pasinskim

**Comment by bahamat** [comment]
I would love to provide a test for this. However, I don't understand the test framework in the slightest. I'm happy to help in any way that I can though.

**Comment by nickanderson** [comment]
Hey @bahamat you might get some test ideas from https://github.com/cfengine/masterfiles/pull/575 its a freebsd ports package module that uses mock data

**Comment by bahamat** [comment]
Yeah, @zofrex pointed me at it a couple of days ago. I've been looking at it.

**Comment by bahamat** [comment]
Ok, I think I've got something that'll work, but I'm sharing some of the framework that @zofrex added so now I have a dependency on #575.

**Comment by kacfengine** [comment]
Should be ready to go again, as discussed on mailing list.

**Comment by kacfengine** [comment]
Merged in #603.

**Pull request merged**
