### PR TITLE
Fix location of the expected result of the set_line_based test

### PR DESCRIPTION
**Pull request by vpodzime**
Ticket: ENT-5866
Changelog: None

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8337/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8337/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8337/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8339/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8339/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8339/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8340/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8340/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8340/

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
