### PR TITLE
ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs (3.15)

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1059

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8029/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8029/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8029/

**Comment by nickanderson** [comment]
Rebased https://github.com/cfengine/buildscripts/pull/1059

**Pull request merged**
