### PR TITLE
CFE-3512/master: Renamed python symlink to cfengine-selected-python

### PR DESCRIPTION
**Pull request by nickanderson**
Package modules that rely on python can be run with either python2 or python3.
We maintain a symlink pointing to a version of python found on the system that
is appropriate. In order to avoid confusion, since CFEngine's bin directory is
commonly found in $PATH we have renamed the symlink so that the symlink is not
used when a user types python on the console.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Review by vpodzime — COMMENTED** [review]
Upgraded installations will have both symlinks, right? Also, please make sure this works properly with upgrades in general.

**Comment by nickanderson** [comment]
> Upgraded installations will have both symlinks, right? Also, please make sure this works properly with upgrades in general.

Ah, yes, this should also cull the old symlink. thanks.

**Comment by nickanderson** [comment]
Added a commit to cleanup the old symlink.

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5991/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5991/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5991/

**Review by olehermanse — APPROVED** [review]
+1

**Review by vpodzime — COMMENTED** [review]
Please squash the first two commits and test that upgrade and self-upgrade works.

**Pull request merged**
