### PR TITLE
CFE-2429: Manage cfengine components via policy on systemd managed hosts

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom test this in jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2856/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2856/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2856/

**Comment by nickanderson** [comment]
@cf-bottom just go ahead and fix whatever is busted

**Comment by cf-bottom** [comment]
I'm not sure I understand, @nickanderson.

**Comment by olehermanse** [comment]
@cf-bottom try one more time in jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2863/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2863/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2863/

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2897/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2897/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2897/

**Comment by olehermanse** [comment]
@cf-bottom another jenkins build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2898/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2898/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2898/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2899/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2899/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2899/

**Pull request merged**
