### PR TITLE
Switch to POSIX compliant shell tool paths on Solaris 9 and 10.

### PR DESCRIPTION
**Pull request by kacf**
CFE-2616

Changelog: Title
Signed-off-by: Kristian Amlie <kristian.amlie@cfengine.com>

### CODE REVIEW

**Comment by kacf** [comment]
Don't merge this yet, I'm still working out the paths.

**Comment by kacf** [comment]
@nickanderson: I have updated the PR, perhaps you can take a look?

@mikeweilgart: Can you try that this works to your expectations?

**Comment by kacf** [comment]
Merging this so we can get it into the beta. Nick didn't think this was a bug fix so this will be in master / 3.11 only.

**Comment by mikeweilgart** [comment]
Great, I like the simplified logic (compared to handling Solaris 11 specially).  Thank you!

**Pull request merged**
