### PR TITLE
Fix acceptance test failing with /opt/cfengine package.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Do not merge yet, I need to test with a special /opt/cfengine package.

**Comment by jimis** [comment]
This was tested and works, merge at will!

**Comment by kacfengine** [comment]
Hehe, clever!

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Spurious errors, but nothing related.

**Comment by kacfengine** [comment]
Cherry-picked to 3.6.x.

**Pull request merged**
