### PR TITLE
ENT-6219 Added default cf_version_release of 1 when sys var missing

### PR DESCRIPTION
**Pull request by craigcomstock**
In versions before 3.12.7 sys.cf_version_release is not present so default to 1.
This will handle most cases well and enable upgrades from <3.12.7 to >=3.12.7.

Ticket: ENT-6219
Changelog: title
(cherry picked from commit 2edd756bc6a9ba769e1912bdb56cc0339a7c9b9c)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6275/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6275/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6275/

**Review by nickanderson — CHANGES_REQUESTED** [review]
The changes here are OK, but can you also `s/ifvarclass/if/g` I see it in the windows self upgrade scheduled file.

In master all the rest of ifvarclass have been replaced with if.

**Comment by craigcomstock** [comment]
> The changes here are OK, but can you also `s/ifvarclass/if/g` I see it in the windows self upgrade scheduled file.
> 
> In master all the rest of ifvarclass have been replaced with if.

Sure. But the proper syntax for `ed(1)` is `g/ifvarclass/s//if/` ;) :)

**Review by nickanderson — APPROVED** [review]

**Pull request merged**
