### PR TITLE
ENT-4177: Updated yum package module to take arbitrary options

### PR DESCRIPTION
**Pull request by olehermanse**
Example:
```
[root@hub vagrant]# nano
bash: /bin/nano: No such file or directory
[root@hub vagrant]# cat test.cf
body file control {
  inputs => {"/var/cfengine/inputs/lib/stdlib.cf"};
}

bundle agent main {
  packages:
    "nano"
      policy => "present",
      package_module => yum,
      architecture => "x86_64",
      options => { "--setopt=tsflags=nodocs" };
}
[root@hub vagrant]# cf-agent -f ./test.cf -IC -K
    info: Successfully installed package 'nano'
[root@hub vagrant]# man nano
No manual entry for nano
[root@hub vagrant]# 
```

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @nickanderson can review this?

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @nickanderson can review this?

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @nickanderson can review this?

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by olehermanse** [comment]
Awaiting feedback from @nickanderson or another policy guru.

**Comment by nickanderson** [comment]
I guess this is how you would set multiple options?

```
    bundle agent main
    {
      packages:
    
          "nano"
            policy => "present",
            package_module => yum,
            architecture => "x86_64",
            options => {
                         "--setopt=tsflags=nodocs",
                         "--setopt=throttle=3M",
                         "--setopt=metadata_expire=2d"
            };
    }
```

**Comment by olehermanse** [comment]
@nickanderson yes, that is how I expect it to work. My problem is that I don't know enough packages and options to use this with :)

**Comment by nickanderson** [comment]
Also, 

I guess that global vs repo specific option works the same?

Set any config option in yum config or repo files. For options in the global config just use: --setopt=option=value for repo options use: --setopt=repoid.option=value

**Comment by olehermanse** [comment]
@nickanderson I don't know how the module protocol works. Whatever is passed as `options=` will be treated in the same way. If you have some policy and an example of a package to test with, I can test it.

**Comment by olehermanse** [comment]
@nickanderson I think this can be merged. Do you think we should cherry-pick?

**Comment by nickanderson** [comment]
Yes

**Comment by nickanderson** [comment]
Merge and pick at will

**Pull request merged**
