### PR TITLE
CFE-3618: Removed unused plugins directory (master)

### PR DESCRIPTION
**Pull request by nickanderson**
merge together: https://github.com/cfengine/buildscripts/pull/814 https://github.com/cfengine/core/pull/4577

The plugins directory has seemingly gone unused since it was introduced to the
MPF in 2013, this change simply removes this directory from being considered for
sharing and updating.

Ticket: CFE-3618
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6309/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6309/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6309/

**Comment by nickanderson** [comment]
@cf-bottom  jenkins, again please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6313/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6313/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6313/

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by vpodzime** [comment]
sequential tests retry: [Build Status](https://ci.cfengine.com/job/sequential-tests/1745/) -- this PR breaks upgrade

**Comment by nickanderson** [comment]
Alrighty @cf-bottom, let's try jenkins again!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6317/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6317/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6317/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again please. I don't believe the test failure had anything to do with my change.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6319/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6319/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6319/

**Comment by nickanderson** [comment]
@olehermanse @vpodzime I think these last two failures are unrelated to my change.

Summary of CI failures:
* [https://ci.cfengine.com/job/pr-pipeline/6313/]
** Legit, believed to be caused by missing access promise because of unresolved variable. Restored that variable, triggered another build.
* [https://ci.cfengine.com/job/pr-pipeline/6317/]
** {{¯\_(ツ)_/¯}} I don't understand the test result, says testing-pr (canary) is red
** following the link to that build [https://ci.cfengine.com/job/testing-pr/13584/]
*** it says test result no failures
** No changes, triggered another build.
* [https://ci.cfengine.com/job/pr-pipeline/6319/]
** Failed valgrind checks?
** [https://ci.cfengine.com/job/valgrind-checks/892/console]

**Comment by nickanderson** [comment]
@cf-bottom I added a separate pr to handle the valgrind failure lets try jenkins again please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6330/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6330/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6330/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
