### PR TITLE
ENT-8603: Stopped loading Apache mod_authz_groupfile by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1063

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7950/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7950/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7950/

**Comment by nickanderson** [comment]
Failed triple upgrade (https://ci.cfengine.com/job/sequential-tests/3920/) and selenium tests (https://ci.cfengine.com/job/testing-run-php-selenium-tests/3612/)

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7985/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7985/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7985/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8027/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8027/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8027/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8045/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8045/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8045/

**Comment by nickanderson** [comment]
Rebased https://github.com/cfengine/buildscripts/pull/1063

@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8049/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8049/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8049/

**Review by craigcomstock — APPROVED** [review]
green!

**Pull request merged**
