### PR TITLE
ENT-8280 Enforce proper owner and perms on docroot

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-8280
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7423/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7423/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7423/

**Comment by craigcomstock** [comment]
All expected/known issues in CI. @vpodzime please review and merge as you wish.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
cherry picks
3.18 https://github.com/cfengine/masterfiles/pull/2240
3.15 https://github.com/cfengine/masterfiles/pull/2241

**Pull request merged**
