### PR TITLE
Fix: rm_rf_depth should also remove the named directory

### PR DESCRIPTION
**Pull request by nickanderson**
Previously it was only removing the contents of the directory.

Ref: https://dev.cfengine.com/issues/7009

### CODE REVIEW

**Comment by nickanderson** [comment]
This should also be picked to 3.6

**Comment by basvandervlies** [comment]
+1

**Comment by kacfengine** [comment]
And cherry-picked to 3.6.x.

**Comment by zerkms** [comment]
Actually it brings some inconsistency now:

      "$(name)"
      file_select => all,
      depth_search => recurse_with_base($(depth)),
      delete => tidy;

      "$(name)/."
        delete => tidy;

As soon as you have a not infinite depth - you cannot guarantee that the directory is empty, hence you cannot perform directory removal.

**Comment by tzz** [comment]
I think the promise outcome may be wrong, but the convergence passes will take care of the removal in either case.

Can you show a counter-example of how this might fail?

**Comment by zerkms** [comment]
For some reason I thought that it will be a warning about being not able to remove the directory.

Just checked it (should have done it before actually) and it does not. So, sorry and nevermind, I was wrong :-)

**Comment by tzz** [comment]
No problem :)  I was just as curious as you, but I've used it so I remembered it worked...

**Pull request merged**
