### PR TITLE
ENT-5045/master: Fixed standalone self upgrade on SUSE 11

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom  jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4011/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4011/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4011/

**Comment by nickanderson** [comment]
@craigcomstock 

In commit a5f70fc7807f158749949a9086054b831c104693 the self upgrade moved to it's own policy entry. Previously packages were upgraded during the run of update.cf. This change moved actual package upgrades to a sub-agent execution. So update.cf would trigger `cf-agent -f standalone_self_upgrade.cf`. As part of the re-factoring the backup_script, backup_file, install_script, and admin_file variables that were in cfe_internal_update_bins moved to cfengine_software_version_packages1. References to the variables were not updated at the time, that's what this change fixes.

**Comment by nickanderson** [comment]
All this jenkins redness :/ surely it's not caused by this fix.

@cf-bottom run this through the jenkins guantlet again, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4018/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4018/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4018/

**Pull request merged**
