### PR TITLE
Fix travis builds.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson I am now getting a different error:

```
./17_packages/01_init/unsafe/timed/001-prepare-repositories.cf Skipped (Unsafe tests are disabled)
./17_packages/11_old/unsafe/timed/inventory_packages_update_frequency.cf Skipped (Unsafe tests are disabled)
./17_packages/12_new/timed/installed-list-cached.cf Awaiting (125 seconds)...
./17_packages/12_new/timed/local-updates-list-cached.cf Awaiting (65 seconds)...
./17_packages/12_new/timed/packagesmatching.cf Awaiting (0 seconds)...
./17_packages/12_new/timed/updates-list-cached.cf Awaiting (125 seconds)...
./00_basics/def.json/control_common_bundlesequence_end.cf /home/travis/.travis/job_stages: line 54:  6762 Terminated              ./testall --agent=/var/cfengine/bin/cf-agent --cfpromises=/var/cfengine/bin/cf-promises --cfserverd=/var/cfengine/bin/cf-serverd --cfexecd=/var/cfengine/bin/cf-execd --cfrunagent=/var/cfengine/bin/cf-runagent --cfkey=/var/cfengine/bin/cf-key --rpmvercmp=/bin/true --printlog
```

Any ideas?

**Comment by nickanderson** [comment]
wth

**Comment by jimis** [comment]
At last, a green build!

**Comment by jimis** [comment]
@nickanderson can you please handle the cherry-picks if more branches in masterfiles are broken?

**Comment by nickanderson** [comment]
Ya I believe it is just the 3.10.x branch that is affected.

**Comment by nickanderson** [comment]
https://github.com/cfengine/masterfiles/pull/920

**Pull request merged**
