### PR TITLE
Set default access promises for directories only if directories exist

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by olehermanse** [comment]
@cf-bottom run this in jenkins and give me some packages!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2578/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2578/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2578/

**Comment by olehermanse** [comment]
@nickanderson cherry-pick?

**Comment by nickanderson** [comment]
YES, PRs up.

**Pull request merged**
