### PR TITLE
Backport feature_def_json_preparse 

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@kacf @tzz please review

**Comment by tzz** [comment]
Looks good to me.

**Comment by kacf** [comment]
Looks good to me as well. Will merge this together with the rest.

**Comment by kacf** [comment]
Closing this, since I merged https://github.com/cfengine/masterfiles/pull/669, which had an additional commit. Let me know if you think I missed anything there.

**Pull request closed without merging**
