### PR TITLE
ENT-7442: Fixup zypper package module script to work properly with interpreter attribute (3.15)

### PR DESCRIPTION
**Pull request by nickanderson**
Same change as included in masterfiles commit

ef02bcb265b7a285b280efddb87413f68372ba2e

which covered apt_get and yum but missed zypper.

Ticket: ENT-7442
Changelog: title
(cherry picked from commit 684ec90b028360a63726ce5fce37629682668c00)

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6872/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6872/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6872/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6901/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6901/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6901/

**Comment by nickanderson** [comment]
Selenium test failure unrelated, merging.

**Pull request merged**
