### PR TITLE
ENT-5752: Modules from MPF

### PR DESCRIPTION
**Pull request by nickanderson**
Trying to debug the original pr https://github.com/cfengine/core/pull/4660/files

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom please try this in jenkins.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6587/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6587/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6587/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6602/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6602/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6602/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6603/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6603/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6603/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6604/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6604/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6604/

**Comment by nickanderson** [comment]
`(╯°Д°)╯︵/(.□ . \)` @cf-bottom please, try jenkins again.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6605/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6605/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6605/

**Comment by nickanderson** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6606/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6606/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6606/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6623/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6623/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6623/

**Pull request closed without merging**
