### PR TITLE
Fixed running clean_when_off commands on all hosts

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-7968

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7426/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7426/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7426/

**Comment by nickanderson** [comment]
Note to self: please pick to 3.18.x and 3.15.x

**Review by vpodzime — COMMENTED** [review]
Looks good to me, but I wonder if we should add this guard to some other place that actually makes `clean_when_off` to be evaluated.

**Comment by nickanderson** [comment]
This is still failing FR tests

**Comment by aleksandrychev** [comment]
@vpodzime can you have a look why FR tests are failing? I don't think it's related to changes

**Comment by craigcomstock** [comment]
If we add something to `entry` bundle instead like

```
    (am_superhub|am_feeder).(am_off|config_not_exists)::
      "CFEngine Enterprise Federation Transport Off"
        handle => "clean_when_off",
        usebundle => clean_when_off;
```

Then I am wondering either way how will `clean_when_off` STOP being called? We aren't using a database table promise so will just keep getting called right? But at least this is an improvement and will fix CI.

**Comment by craigcomstock** [comment]
trying a similar change as @vpodzime proposed: https://github.com/cfengine/masterfiles/pull/2204

**Comment by aleksandrychev** [comment]
@craigcomstock  I see you almost resolved issue there https://github.com/cfengine/masterfiles/pull/2204. I will close this one

**Pull request closed without merging**
