### PR TITLE
Fix apt_get package module incorrectly using interactive mode.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: Title
Signed-off-by: Kristian Amlie <kristian.amlie@cfengine.com>

### CODE REVIEW

**Comment by jimis** [comment]
Jenkins disagrees:

```
00:26:49.459 FAIL: test_package_module_apt_get
00:26:49.459 =================================
00:26:49.459 
00:26:49.459 Fail: Does not appear in mock log: "dpkg -i /path/to/pkg"
00:26:49.459 Actual output:
00:26:49.459 "dpkg --force-confold --force-confdef -i /path/to/pkg
00:26:49.459 "
00:26:49.459 Traceback (most recent call last):
00:26:49.459   File "./test_package_module_apt_get", line 94, in <module>
00:26:49.459     assert check("file-install", ["File=/path/to/pkg"], 0, [], 1, ["dpkg -i /path/to/pkg"])
00:26:49.459 AssertionError
```

**Comment by zofrex** [comment]
I reported this bug on IRC this morning - here's the error log I posted:

```
Configuration file '/etc/inspircd/inspircd.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** inspircd.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package inspircd (--install):
 EOF on stdin at conffile prompt
Errors were encountered while processing:
 inspircd
    info: Some error occurred while communicating with package module while installing package.
   error: Error installing package '/root/inspircd_2.0.23-1_amd64.deb'
```

What the log file is showing is a package failing to install. The context leading up to the failure is that the configuration file was created first, then the package was installed, using the "apt_get" package module but installing from a .deb file, not using apt-get and a repo. The cause of the failure is dpkg spawning an interactive prompt asking what to do with the configuration file, which the package module (obviously) doesn't respond to correctly.

After reporting this on IRC this PR was made and I was asked to test it.

I just did some manual testing on the same setup that produced the above, and can confirm this fix works - it now keeps the existing config file and installs the package, which is (imo) the expected behaviour here.

**Comment by kacf** [comment]
Thanks for testing @zofrex!

Pull request updated to fix the unit test failure, and started new build in Jenkins.

**Comment by jimis** [comment]
Jenkins is green now, merging. Thanks!

**Comment by jimis** [comment]
Cherry-picked in all maintained branches.

**Pull request merged**
