### PR TITLE
CFE-3568: Miscellaneous fixes for FreeBSD's pkg package module (master)

### PR DESCRIPTION
**Pull request by gpiero**
After the application of these patches:

- cfengine properly reports that a packages promise has been correctly repaired in case of package upgrade or if the architecture has been explicitly declared in the promise
- the repository option is not ignored anymore

### CODE REVIEW

**Comment by gpiero** [comment]
> - a new 'jail' option is supported (but not currently working because of https://tracker.mender.io/browse/CFE-3533)

mmh, no... after thinking a bit, I suspect it wouldn't work even if CFE-3533 was fixed, unless always forcing the update (so, ignoring the lock constraints): I guess the package cache shared between the host and all the jails would be a problem.

The other patches are still valid, though.

**Comment by nickanderson** [comment]
Hi @gpiero , do you want to drop your last commit so we can look to take these other fixes in?

**Comment by gpiero** [comment]
Dropped last commit (so, no 'jail' option anymore) and rebased on the top of current cfengine:master.

**Comment by nickanderson** [comment]
Hi @gpiero, getting back around to looking at this one. 

Can you please provide some example usage e.g.:

```
packages:
  "nginx-full"
    policy => "present",
    options => 
    classes => results( "bundle", "my_example" );

reports:
  "Classes: $(with)" with => join( ", " classesmatching( "my_example_.*" ) );
```

Showing output before and after your patches.

**Review by nickanderson — CHANGES_REQUESTED** [review]
Hi @gpiero, getting back around to looking at this one. 

Can you please provide some example usage e.g.:

```
packages:
  "nginx-full"
    policy => "present",
    options => 
    classes => results( "bundle", "my_example" );

reports:
  "Classes: $(with)" with => join( ", " classesmatching( "my_example_.*" ) );
```

Showing output before and after your patches.

**Comment by gpiero** [comment]
Sorry for being silent so long. It's in my todo list but frankly at a quite low priority at the moment.
Will followup as soon as I'll have some time to devolve to the activity.

**Comment by gpiero** [comment]
[CFE-3568-after.log](https://github.com/cfengine/masterfiles/files/6175696/CFE-3568-after.log)
[CFE-3568-before.log](https://github.com/cfengine/masterfiles/files/6175698/CFE-3568-before.log)
[CFE-3568.txt](https://github.com/cfengine/masterfiles/files/6175702/CFE-3568.txt)

Please find attached the cf file (renamed to .txt because Github), and the before and after results.
Note that:
- in the first 2 tests (install_architecture and update) cfengine could not recognize the promise was repaired despite the package had been correctly installed
- in the 3rd test (install_repository) the package had been installed despite not existing in the referred repository (the repository option was ignored)

**Comment by nickanderson** [comment]
I opened https://github.com/cfengine/masterfiles/pull/1957 to supersede this PR. The only differences are re-written commit messages. Tagged this PR with `onhold` until the other one is merged, then will close this one.

**Comment by nickanderson** [comment]
@gpiero I am closing this PR. We finally merged https://github.com/cfengine/masterfiles/pull/1957 which I believe superseded this PR.

If you have other changes here not found in https://github.com/cfengine/masterfiles/pull/1957 we should get a new ticket and PR up.

**Pull request closed without merging**
