### PR TITLE
Keys must always be pre-generated.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
@nickanderson please review

**Comment by nickanderson** [comment]
Ref: https://dev.cfengine.com/issues/7167

**Comment by jimis** [comment]
So does it make sense to have `cf-key` being run from `update.cf`? I don't think so, personally...

**Comment by nickanderson** [comment]
@jimis Does this need to goto 3.7.x also?

**Comment by jimis** [comment]
cherry-picked to 3.7.x.

**Pull request merged**
