### PR TITLE
ENT-6536: Shortened Inventory OS attribute to be more readable

### PR DESCRIPTION
**Pull request by olehermanse**
Tested on:

- [x] Ubuntu 14
- [x] Ubuntu 16
- [x] Ubuntu 18
- [x] Ubuntu 20
- [x] Debian 7
- [x] Debian 8
- [x] Debian 9
- [x] Debian 10
- [x] RHEL 5
- [x] RHEL 6
- [x] RHEL 7
- [x] RHEL 8
- [x] CentOS 6
- [x] CentOS 7
- [x] Windows 2012
- [x] Windows 2016
- [x] SUSE 11
- [x] SUSE 12
- [x] SUSE 15

OS strings are as shown ^

### CODE REVIEW

**Comment by olehermanse** [comment]
Created a follow-up ticket: https://tracker.mender.io/browse/ENT-6658

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6013/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6013/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6013/

**Comment by olehermanse** [comment]
@nickanderson ready for review.

**Review by nickanderson — APPROVED** [review]

**Comment by nickanderson** [comment]
I am still not 100% convinced that this should be in the MPF, but not enough doubts to reject it.

**Pull request merged**
