### PR TITLE
ENT-6966 Re-enabled *-list-cached tests (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7400/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7400/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7400/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins one more time (without those problematic platforms)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7403/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7403/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7403/

**Pull request merged**
