### PR TITLE
CFE-3238/master: Standard services now considers systemd services with ActivState=activating active

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4529/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4529/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4529/

**Comment by nickanderson** [comment]
Travis failure is because of nightly build failure, so mpf test fails to validate policy with missing nightly package.

**Comment by nickanderson** [comment]
Thanks @basvandervlies

**Pull request merged**
