### PR TITLE
ENT-8393 Fixed inclusion of distributed cleanup python files during install

### PR DESCRIPTION
**Pull request by craigcomstock**
configure.ac was missing entry

controls/update.cf already includes *.py so OK there.

Ticket: ENT-8393
Changelog: title

### CODE REVIEW

**Comment by nickanderson** [comment]
Do we need this? I found the files in the tarball so something is getting them into place.

**Comment by craigcomstock** [comment]
> Do we need this? I found the files in the tarball so something is getting them into place.

Yes. I checked the latest nightly masterfiles tarball and these scripts are missing. I'll test make tar-ball locally and check.

**Comment by craigcomstock** [comment]
`make tar-package` in master does indeed miss these python files in templates dir. So this change is needed.

**Review by nickanderson — APPROVED** [review]
Alrighty then.

Wonder how I got the files in my repo as untracked files then.

**Comment by craigcomstock** [comment]
only 3.18 cherry pick was needed: https://github.com/cfengine/masterfiles/pull/2247

**Pull request merged**
