### PR TITLE
Added new generation package_module for FreeBSD.

### PR DESCRIPTION
**Pull request by fbettag**
This script adds support for the new package promise on FreeBSD. It also fixes https://dev.cfengine.com/issues/7421.

Thanks for your consideration.

### CODE REVIEW

**Comment by tzz** [comment]
nice!

**Comment by kacf** [comment]
I have little experience with FreeBSD, so I may be wrong about this, but doesn't this module step on the toes of https://github.com/cfengine/masterfiles/pull/575? Both use the `pkg` command.

**Comment by fbettag** [comment]
@kacf: Yes and no. :)
#575 apparently leverages [portsnap](https://github.com/zofrex/masterfiles/commit/e30c55f2bf84f058f569c5ec16885a4227671236#diff-64bdd1f24ebd3cd695826a79c30e78e3R50) which is the source variant of packaging. #575 takes care of downloading Makefiles and build packages using them and uses "pkg" to install/list/deinstall them. It **doesn't** download (for example) cfengine's Makefile, but a Makefile which describes to FreeBSD ports-system how to handle CFengine's configure/Makefile/etc. In short: It deals with Wrapper-Scripts that result in compiled packages.

My version takes care of the binary backend, where no "Makefiles" get downloaded, just plain and simple binary packages that are prebuilt (by either yourself or the official repo). This also uses "pkg" but a bit more extensive than #575.

The difference is also in naming. #575 uses "freebsd ports" (which is the name for the source form of 3rd party software), while mine is "pkgng" which only takes care of pre-built binaries.

**Comment by kacf** [comment]
Ok, thanks for explaining. It sounds like it's natural that they live side by side.

But what about #620? That one looks very similar to this one.

**Comment by fbettag** [comment]
@kacf Yes, they live side by side, giving the admin the option to either build packages specific to their needs on their boxes (like #575 offers) or prebuild their own/use stock packages (like we do).

Yes #620 is conflicting with this one, does the same as mine but i am not qualified enough to judge which one is better from the cfengine standpoint. (sure hope its mine lol)

**Comment by fbettag** [comment]
Also to make it more clearer, they don't live "together". They are the same thing "pkg".
pkg is like the dpkg command. It takes care of the database of installed packages and all operations around it.

Portsnap (as used in #575) just has the extra advantage of using source-based-packages (from which all binary packages get built) as different source. Both ways end up installing their packages through "pkg". It's just about how you get from "i want package X" to the resulting binary package which gets installed. :)

**Comment by kacf** [comment]
> Yes #620 is conflicting with this one, does the same as mine but i am not qualified enough to judge which one is better from the cfengine standpoint.

I will have a look at this later. But this point may become moot. See additional discussion in #575.

**Comment by kacf** [comment]
Closing this in favor of #620.

**Pull request closed without merging**
