### PR TITLE
ENT-5406/master: Fixed use of standard_services service_method in federation policy

### PR DESCRIPTION
**Pull request by nickanderson**
This change makes sure that standard_services service_method from the default
namespace is used when trying to manage services. Prior to this change, it was
trying to use standard_services service method from the
cfengine_enterprise_federation namespace.

Ticket: ENT-5406
Changelog: None

----

#

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4855/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4855/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4855/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4858/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4858/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4858/

**Pull request merged**
