### PR TITLE
ENT-8522: Stopped loading Apache mod_env by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1017

We do not use the features provided by this module, so we should not load it by
default.

Ticket: ENT-8522
Changelog: Title

### CODE REVIEW

**Review by aleksandrychev — APPROVED** [review]

**Comment by aleksandrychev** [comment]
```This module allows for control of internal environment variables that are used by various Apache HTTP Server modules. These variables are also provided to CGI scripts as native system environment variables, and available for use in SSI pages. Environment variables may be passed from the shell which invoked the [httpd](https://httpd.apache.org/docs/2.4/programs/httpd.html) process. Alternatively, environment variables may be set or unset within the configuration process.```

Please run tests before merging and see if php ones are green

**Comment by nickanderson** [comment]
> `This module allows for control of internal environment variables that are used by various Apache HTTP Server modules. These variables are also provided to CGI scripts as native system environment variables, and available for use in SSI pages. Environment variables may be passed from the shell which invoked the [httpd](https://httpd.apache.org/docs/2.4/programs/httpd.html) process. Alternatively, environment variables may be set or unset within the configuration process.`
> 
> Please run tests before merging and see if php ones are green

@aleksandrychev

**Comment by nickanderson** [comment]
> `This module allows for control of internal environment variables that are used by various Apache HTTP Server modules. These variables are also provided to CGI scripts as native system environment variables, and available for use in SSI pages. Environment variables may be passed from the shell which invoked the [httpd](https://httpd.apache.org/docs/2.4/programs/httpd.html) process. Alternatively, environment variables may be set or unset within the configuration process.`
> 
> Please run tests before merging and see if php ones are green

It fails the same triple upgrade test (`new_tests/sequential_tests/03-upgrade-minor.01-upgrade-minor.test`
) that @Lex-2008 has been working on.

**Pull request merged**
