### PR TITLE
Revert "ENT-9665: Added /opt/cfengine/build ownership and permissions promises"

### PR DESCRIPTION
**Pull request by olehermanse**
Reverts cfengine/masterfiles#2562

### CODE REVIEW

**Comment by olehermanse** [comment]
Opening this to see if it improves the current state. I am thinking that since we reverted the default perms in cf-reactor, this masterfiles patch is no longer needed.

Should fix:
https://tracker.mender.io/browse/ENT-9714

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9118/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9118/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9118/

**Comment by olehermanse** [comment]
Tested manually, seems to work as expected.

**Review by aleksandrychev — APPROVED** [review]

**Pull request merged**
