### PR TITLE
Add amazon_linux class to yum package module

### PR DESCRIPTION
**Pull request by ageorgop**

### CODE REVIEW

**Comment by ageorgop** [comment]
Add Amazon linux to yum package module

**Comment by ageorgop** [comment]
Added the Changelog entry

**Comment by nickanderson** [comment]
Thanks, one last thing, can you squash your 3 commits down to 1? (don't forget to preserve the changelog entry).

**Comment by nickanderson** [comment]
ping @ageorgop  for squashing. else ill do it in coming days.

**Comment by nickanderson** [comment]
Squashed here: https://github.com/cfengine/masterfiles/pull/1057

**Pull request closed without merging**
