### PR TITLE
CFE-3237 Update modules from masterfiles

### PR DESCRIPTION
**Pull request by Lex-2008**
try two

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5037/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5037/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5037/

**Comment by Lex-2008** [comment]
of course it won't work! There is no `modules` in masterfiles!
```
[vagrant@hub ~]$ sudo ls -la /var/cfengine/masterfiles/
total 104
drwx------.  8 root root  4096 Apr 22 21:48 .
drwxr-xr-x. 20 root root  4096 Apr 22 21:48 ..
drwx------.  5 root root  4096 Apr 22 21:48 cfe_internal
-rw-------.  1 root root    61 Apr 22 21:48 cf_promises_release_id
-rw-------.  1 root root    29 Apr 22 21:54 cf_promises_validated
drwx------.  2 root root  4096 Apr 22 21:48 controls
drwx------.  2 root root  4096 Apr 22 21:48 inventory
drwx------.  2 root root  4096 Apr 22 21:48 lib
-rw-------.  1 root root 12703 Apr 22 21:48 promises.cf
drwx------.  3 root root  4096 Apr 22 21:48 services
-rw-------.  1 root root 37251 Apr 22 21:48 standalone_self_upgrade.cf
drwx------.  3 root root  4096 Apr 22 21:48 templates
-rw-------.  1 root root  6178 Apr 22 21:48 update.cf
```

**Comment by Lex-2008** [comment]
almost-green pipeline: https://ci.cfengine.com/job/pr-pipeline/5039/
bootstrap tests failed in another place: https://ci.cfengine.com/job/bootstrap-tests/1104/

I believe this can be merged. @craigcomstock , @nickanderson : opinions?

**Comment by craigcomstock** [comment]
> looks good to me, let's see how it fares in CI +1

Looks like only travis failed, and that because of our ongoing issue with publishing master community packages. (https://tracker.mender.io/browse/ENT-5545)

**Pull request merged**
