### PR TITLE
CFE-3992: Skip package-inventory test on aarch64 platform

### PR DESCRIPTION
**Pull request by craigcomstock**
Need to generate package files.

Ticket: CFE-3992
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8111/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8111/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8111/

**Review by vpodzime — COMMENTED** [review]
I think it would make more sense to do another `(!....!...)` for the platforms we have packages for.

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by craigcomstock** [comment]
> I think it would make more sense to do another `(!....!...)` for the platforms we have packages for.

Cool. Switched the logic up. Checking CI. :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8112/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8112/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8112/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8114/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8114/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8114/

**Pull request merged**
