### PR TITLE
CFE-3161/master: Added ability to avoid limiting robot agents

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by nickanderson** [comment]
These commits were originally in with the un-reversion of the systemd management
fix. They were also needed in order to bypass the valgrind errors.

Maybe you want to remove them from 
https://github.com/cfengine/masterfiles/pull/1539

then we can look at just the systemd change alone.

**Comment by nickanderson** [comment]
@cf-bottom please test this with jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2858/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2858/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2858/

**Comment by olehermanse** [comment]
@cf-bottom try one more jenkins build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2862/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2862/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2862/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2865/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2865/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2865/

**Pull request merged**
