### PR TITLE
Fixed psql not found while FR import

### PR DESCRIPTION
**Pull request by aleksandrychev**
ChangeLog: Title

Ticket: ENT-8353

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7534/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7534/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7534/

**Review by craigcomstock — APPROVED** [review]
yep, thanks for the fix to my earlier commit that introduced the bug: https://github.com/cfengine/masterfiles/commit/ad83552cec64b507251422b692d49f669d56a069

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by craigcomstock** [comment]
3.15.x and 3.18.x need this fix as well since my buggy commit also went to those branches.

**Comment by craigcomstock** [comment]
cherry picks are already done:
3.18 - https://github.com/cfengine/masterfiles/pull/2233
3.15 - https://github.com/cfengine/masterfiles/pull/2234

**Pull request merged**
