### PR TITLE
ENT-6786: Minor improvements related to host specific data from cmdb generation

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Review by craigcomstock — APPROVED** [review]
looks reasonable to me :+1:

**Comment by nickanderson** [comment]
@Lex-2008 can you add these to channels please

**Comment by nickanderson** [comment]
Changelog

**Comment by nickanderson** [comment]
oh sorry @Lex-2008  nevermind, they don't need to be in the changelog, they are inconsequential since no release has happened.

**Pull request merged**
