### PR TITLE
Fix cfe watchdog (cron version) to be more robust against edge cases

### PR DESCRIPTION
**Pull request by mikeweilgart**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @nickanderson can review this?

**Comment by vpodzime** [comment]
@nickanderson please review this and feel free to merge right away.

**Comment by nickanderson** [comment]
This is good, but I would like a ticket to document the change as well. I will create and then ask for a re-word.

**Comment by nickanderson** [comment]
OK, I created https://tracker.mender.io/browse/CFE-3258 for documenting this.

@mikeweilgart can you please squash and re-word the commits adding [metadata for our changelog generator|https://github.com/cfengine/core/blob/master/CONTRIBUTING.md#commit-message-example]?

**Comment by nickanderson** [comment]
Superceeded by https://github.com/cfengine/masterfiles/pull/1676 which adds metadata for changelog generator.

Thanks @mikeweilgart !

**Pull request closed without merging**
