### PR TITLE
ENT-4266 Switch to runalerts_all

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by craigcomstock** [comment]
@nickanderson it would be good to know how this interacts with some other part of the system. Is this just a cosmetic name change? g/sql/s//all/g?

**Comment by nickanderson** [comment]
@craigcomstock It was in relation to ENT-4266 where @aleksandrychev swtiched to runalerts all from runalerts sql.

**Comment by nickanderson** [comment]
@aleksandrychev  please review, and what brahces should this goto?

**Comment by aleksandrychev** [comment]
> what brahces should this goto?

3.13.x and master.

**Comment by nickanderson** [comment]
Really? What about 3.12.x?

**Comment by nickanderson** [comment]
Nevermind, i checked. runalert.php is doing sql and sketch https://github.com/cfengine/masterfiles/blob/3.12.x/cfe_internal/enterprise/templates/runalerts.php.mustache

**Pull request merged**
