### PR TITLE
ENT-6966 - test ENT-7359 changes with re-enabling tests

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7264/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7264/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7264/

**Comment by craigcomstock** [comment]
Let's try this again with exotics @cf-bottom , because I suspect PACKAGES_ia64_hpux_11.23 and PACKAGES_ppc64_aix_53 need to be fixed, but if the others work a few times maybe we can re-enable those.

**Comment by cf-bottom** [comment]
I'm not sure I understand, @craigcomstock.

**Comment by craigcomstock** [comment]
Darn. @cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7273/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7273/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7273/

**Comment by craigcomstock** [comment]
Stopped this build. ENT-7359 is already merged in master so no need for this now and I have another change which I think will improve ia64_hpux and aix_53 situations most likely.

**Pull request closed without merging**
