### PR TITLE
ENT-7261: Adjusted permissions for Mission Portal public tmp files

### PR DESCRIPTION
**Pull request by nickanderson**
Merge with:
https://github.com/cfengine/mission-portal/pull/1493#pullrequestreview-729737292

Mission Portal creates bundled js files when exporting reports.

The webserver needs read access to these files but they don't need to be
readable or writeable by anyone.

This adjustment was made to align the permissions of files created by Mission
Portal with those promised in the policy in order to avoid un-necessary repairs.

Ticket: ENT-7261
Changelog: Title

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7039/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7039/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7039/

**Review by aleksandrychev — APPROVED** [review]
lgtm

**Comment by nickanderson** [comment]
Test failure is unrelated to this change.

**Pull request merged**
