### PR TITLE
Fixed mock test for apt_get package module

### PR DESCRIPTION
**Pull request by nickanderson**
Recently switched to using apt_get instead of dpkg for local file installs so
that dependencies would be resolved automatically, and so that the behavior was
more in line with user expectations without having to read something.

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom take this and see if it will blend in jenkins, please.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6990/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6990/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6990/

**Comment by nickanderson** [comment]
@cf-bottom take this and see if it will blend in jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7000/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7000/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7000/

**Review by craigcomstock — APPROVED** [review]
@nickanderson I think we should merge this change. I need it to pass CI on this one I think: https://github.com/cfengine/core/pull/4768

**Comment by craigcomstock** [comment]
Rebuilding after adding i386 architecture to ubuntu 16 buildslave in CI.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/7012/)

**Pull request merged**
