### PR TITLE
Change: Re-organize controls

### PR DESCRIPTION
**Pull request by nickanderson**
Complete split of controls and relocate update_def.cf into controls/VER for
consistency.

Switch to classic array definition of control inputs to make it easier to
exclude extra input files that are not necessary on community installs and
make the function of each control input more clear within the policy.

### CODE REVIEW

**Comment by nickanderson** [comment]
@estenberg for your review

**Comment by nickanderson** [comment]
trigger build

**Comment by estenberg** [comment]
Looks good, makes sense. :+1:

**Comment by nickanderson** [comment]
trigger build

**Comment by nickanderson** [comment]
great, soson as i verify it through the build system will merge

**Pull request merged**
