### PR TITLE
ENT-8601: Stopped loading Apache mod_authn_dbd by default on Enterprise Hubs

### PR DESCRIPTION
**Pull request by nickanderson**
Merge Together:
- https://github.com/cfengine/buildscripts/pull/1057

We do not use the features provided by this module, so we should not load it by default.

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7949/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7949/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7949/

**Comment by nickanderson** [comment]
The failure here was selenium tests: https://ci.cfengine.com/job/testing-run-php-selenium-tests/3610/

**Comment by craigcomstock** [comment]
I see 5 failures there but only two are known issues in https://tracker.mender.io/browse/ENT-7579

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7987/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7987/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7987/

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
