### PR TITLE
Fix the noise from attempts to parse lldpctl's stderr as json

### PR DESCRIPTION
**Pull request by mikeweilgart**
See https://tracker.mender.io/browse/CFE-3103 for background.

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @nickanderson can review this?

**Comment by mikeweilgart** [comment]
Actually, I will add that *nothing* in policy uses this information, and it is not tagged for collection.  I recommend turning it off by default.  It's just overhead and it can't be used for anything without policy being written for that.  If someone is writing policy for that, they will know it, and can explicitly add some class to enable this code.

**Comment by nickanderson** [comment]
Does the methodology described in CFE-3109 not work for you?
https://tracker.mender.io/browse/CFE-3109

**Comment by mikeweilgart** [comment]
I don't understand why this should be enabled by default.  Literally nothing in policy uses it, and it's not tagged for collection by the Hub, so if a command is run in the forest but nothing depends on it and the output isn't collected, then why not just leave it disabled by default to avoid the performance overhead of falling trees?  (*We've* disabled it now in our code using def.json to define the disabling class, but I don't think that should be necessary.  The default should be for it NOT to run.)

**Comment by nickanderson** [comment]
Superceeded by https://github.com/cfengine/masterfiles/pull/1493

**Pull request closed without merging**
